### ISSUE TITLE
Segmentation fault with 'kalibr_calibrate_rs_cameras' and 'kalibr_calibrate_cameras'

### ISSUE THREAD

**Issue by ParthaEth** [ethz-asl/kalibr#102]
Hi ,

I have to following error while trying to calibrate a rolling shutter android phone camera. I cloned the current master, compiled it with ros indigo and ubuntu 14.04. Any advise? 

/home/partha/kalibr_workspace/devel/lib/python2.7/dist-packages/aslam_cv_backend/__init__.py:9: RuntimeWarning: to-Python converter for boost::shared_ptr<aslam::backend::DesignVariableAdapter<aslam::cameras::OmniProjection<aslam::cameras::FovDistortion> > > already registered; second conversion method ignored.
  
/home/partha/kalibr_workspace/devel/lib/python2.7/dist-packages/aslam_cv_backend/__init__.py:9: RuntimeWarning: to-Python converter for boost::shared_ptr<aslam::backend::DesignVariableAdapter<aslam::cameras::GlobalShutter> > already registered; second conversion method ignored.
  
/home/partha/kalibr_workspace/devel/lib/python2.7/dist-packages/aslam_cv_backend/__init__.py:9: RuntimeWarning: to-Python converter for boost::shared_ptr<aslam::backend::DesignVariableAdapter<aslam::cameras::RollingShutter> > already registered; second conversion method ignored.
  
Segmentation fault (core dumped)

**Comment by kevin0932** [comment]
Hi @ParthaEth, did you figure out how to solve the problem? I met this similar problem also with ros indigo and Ubuntu 14.04 when using the current master branch of Kalibr. Just no clue what causes the issue. The only message is "Import libraries; \n Segmentation fault (core dumped)". I used it with ros kinetic and Ubuntu 16 successfully before. Thanks for your information.
