### ISSUE TITLE
How camera imu translation is calculated?

### ISSUE THREAD

**Issue by flankechen** [ethz-asl/kalibr#108]
Sorry for the silly question. 
imu gives only rad/s and m/s^2. In a rigid body, the translation between camera and imu should not affect the relation between imu radian and accelation and vision estimated radian and accelation. How the translation is calculated? or it's just mathematics terms which have no phyiscal meaning?
Thanks!

**Comment by goldbattle** [comment]
Acceleration can be integrated over time to recover position. This change in position in the IMU can be compared to the change in position of the CAMERA relative to the calibration board to find the transform between the two (hand eye calibration problem).
