### ISSUE TITLE
questions regard to IMU configuration

### ISSUE THREAD

**Issue by twomol** [ethz-asl/kalibr#143]
We need to specify accelerometer_random_walk, gyroscope_random_walk in IMU.yaml, accelerometer and gyroscope both have 3 axis, there shoud be 3 values for each parameter, but IMU.yaml only ask one how each, how should specify it, the average of X,Y,Z axis?

**Comment by cynosure4sure** [comment]
I usually go with highest one for each in the 3-axis thinking it will act as an upper-bound for the noise/bias along the 3-axis.
Looking forward to a better method as well.
