### ISSUE TITLE
IMU Camera Calibration - Bag Creation

### ISSUE THREAD

**Issue by bdjohnson529** [ethz-asl/kalibr#146]
kalibr_bagcreater functions differently than in documentation. "./" is necessary following dataset repository to successfully create bag.

Works:
kalibr_bagcreater --folder dataset-dir/. --output-bag awsome.bag

Does not work:
kalibr_bagcreater --folder dataset-dir --output-bag awsome.bag

**Comment by jameswalmsley** [comment]
Thanks! That really helped me out..

**Comment by bdjohnson529** [comment]
Glad it helped. This technique applies when KALIBR is installed via CDE package.

**Comment by GabHoo** [comment]
THIS is awsome and SOO important!
Thankyou

**Comment by goldbattle** [comment]
Wiki has been updated.
