### ISSUE TITLE
Zero error and bias

### ISSUE THREAD

**Issue by bdjohnson529** [ethz-asl/kalibr#150]
I am using the cam-imu calibration tool, collecting data at 30 Hz. Camera and IMU are triggered to collect data simultaneously.

The accelerometer and gyroscope errors are determined to be zero after the calibration (1e-14). This can't be accurate. Can the tool calibrate the camera and IMU correctly if IMU data is collected at 30 Hz?

I know there is something wrong with my IMU data collection. Any help is appreciated.

**Comment by goldbattle** [comment]
Sounds like an issue with your data, I would recommend inspecting it, and providing a bag if still an issue.
