### ISSUE TITLE
Problems with IMU parameters setting

### ISSUE THREAD

**Issue by KevinGHub** [ethz-asl/kalibr#156]
Hey guys, I am using rovio with monocular and IMU MTi 100. When I try to set my IMU parameters according to [https://github.com/ethz-asl/kalibr/wiki/IMU-Noise-Model](url), I found the gyroscope_noise_density and accelerometer_noise_density here [https://www.xsens.com/download/pdf/documentation/mti-100/mti-100-series.pdf](url). As for gyroscope_random_walk, I refer to one of the papers below [http://www.acsu.buffalo.edu/~johnc/gpsins_gnc05.pdf](url) where I can't find how accelerometer_random_walk is computed. Or can  the AD graph in [https://www.xsens.com/tags/gyroscopes/](url) help in order to get accelerometer_random_walk? I have been stuck here quite a long time. Appreciate it if you can help.

**Comment by KevinGHub** [comment]
I guess I have figured it out. Those're both illustrated in the wiki. So close.

**Comment by NikolausDemmel** [comment]
Would you mind sharing your conclusion?

**Comment by shilei001** [comment]
Would you mind sharing your conclusion？
