### ISSUE TITLE
Typo in CameraCalibrator.py

### ISSUE THREAD

**Issue by versatran01** [ethz-asl/kalibr#16]
kalibr / aslam_offline_calibration / kalibr / python / kalibr_camera_calibration / CameraCalibrator.py
in line 97
selfgrid should be self.grid

**Comment by NikolausDemmel** [comment]
what wrong with the drawing?

**Comment by versatran01** [comment]
@NikolausDemmel 
The pattern size is wrong, it is resolved in #28.
