### ISSUE TITLE
Equidistance lens distortion 

### ISSUE THREAD

**Issue by fmohammadi2g** [ethz-asl/kalibr#163]
Hi, 

Is equidistance lens distortion is equal to opencv fisheye lens distortion model?
if do calibrate my camera with pinhole-equi , can I use the distortion coefficients in cv::fisheye::undistortimage to undistort my images?

**Comment by YonatanSimson** [comment]
So it seems. Take alook at this conversation: https://github.com/ethz-asl/kalibr/issues/256
