### ISSUE TITLE
kalibr_calibrate_cameras

### ISSUE THREAD

**Issue by jsonvillanueva** [ethz-asl/kalibr#164]
The sample tar, "static", works properly.

A similar bag file is used with a checkerboard.yaml file that matches the checkerboard in use. Strangely, when running the command with the correct --bag, --target, --topics, and --models, the script gets stuck.
`Extracting calibration target corners`
`  Progress 7 / 87        Time remaining: 7s`
It always gets stuck on image 7/N := N is the total number of images in topic. This has been the case with a single topic, alternating models (e.g. pinhole-equi vs pinhole-radtan), altered bag file frame rates (and thus total number of frames, N). There's no error or otherwise, and htop/top suggest the script is not using any of the cpu (though it is with the sample "static").

This is run on Ubuntu 16.04.

**Comment by JianFeiING** [comment]
I have the same issue. I used a custom checkerboard.yaml file, had two cameras to calibrate. I tried several bagfiles, the scripts stuck on image 7/N.

**Comment by ank95** [comment]
Hi 
I am also encountering a similar problem. The script gets stuck at 3/N. Were you able to fix the issue?

**Comment by schneith** [comment]
I am not able to reproduce the problem with my datasets. I'll have a look if you upload a dataset with which I can reproduce the issue.

**Comment by pedropro** [comment]
I just had the same problem with: 
`kalibr_calibrate_imu_camera --cam chain.yaml --target checkerboard.yaml --imu imu.yaml --bag static.bag`
Simply adding the option `--show-extraction` solved it. In my case:
`kalibr_calibrate_imu_camera --cam chain.yaml --target checkerboard.yaml --imu imu.yaml --bag static.bag --show-extraction`

Something to do with the window.

**Comment by jsonvillanueva** [comment]
Adding --show-extraction only shows the GUI. If your calibration target is not properly illuminated, or if the checkerboard target is not in the entire image/too far away, the script fails/freezes as the target corners are not detected.

There's more liberty with using an AprilGrid, especially in the case where the cameras don't overlap much at all which was my issue. Fixing the sensor mounts for more overlap also fixes the issue.
