### ISSUE TITLE
IMU Camera Calibration - Transformation matrix

### ISSUE THREAD

**Issue by panolser** [ethz-asl/kalibr#167]
baseline: [[ 0.99559597 -0.0930107   0.01173568 -0.25246   ]
 [ 0.0929903   0.99566444  0.00227416 -0.00995   ]
 [-0.01189632 -0.00117284  0.99992857  0.001506  ]
 [ 0.          0.          0.          1.        ]]

Distance between camera0 and camera1 0.25

imu is located between the cameras
Distance between camera0 and imu 0.12-0.14
Distance between camera1 and imu 0.12-0.14
This is seen from the last column in T_cam0_imu0:
[[ 0.99920146 -0.03330975 -0.02206602  0.01643918]
 [-0.02221355 -0.00406528 -0.99974498 -0.0176589 ]
 [ 0.03321155  0.99943681 -0.00480196  0.12611205]
 [ 0.          0.          0.          1.        ]]
But in T_cam1_imu0 :
Transformation T_cam1_imu0 (imu0 to cam1, T_ci): 
[[ 0.99725678 -0.02105586  0.07096179 -0.23297074]
 [ 0.07087432 -0.00487226 -0.99747335 -0.02571685]
 [ 0.02134841  0.99976643 -0.00336658  0.12743418]
 [ 0.          0.          0.          1.        ]]
in the last column there is a number(-0.2329) close to the distance between the cameras (0.23-0.25), although the remaining column values are correct.

##  T_cam1_imu0  is correct?

-------------------------------------------------
Calibration results
===================
Normalized Residuals
----------------------------
Reprojection error (cam0):     mean 0.518065940595, median 0.47285569678, std: 0.290909587878
Reprojection error (cam1):     mean 0.254323541071, median 0.201934355932, std: 0.223175609204
Gyroscope error (imu0):        mean 6.50838088524e-10, median 3.02942376581e-10, std: 8.7475171817e-10
Accelerometer error (imu0):    mean 1.1564287342e-10, median 3.56474028369e-11, std: 2.9274636471e-10

Residuals
----------------------------
Reprojection error (cam0) [px]:     mean 0.518065940595, median 0.47285569678, std: 0.290909587878
Reprojection error (cam1) [px]:     mean 0.254323541071, median 0.201934355932, std: 0.223175609204
Gyroscope error (imu0) [rad/s]:     mean 2.1152237877e-12, median 9.84562723888e-13, std: 2.84294308405e-12
Accelerometer error (imu0) [m/s^2]: mean 7.51678677229e-12, median 2.3170811844e-12, std: 1.90285137061e-11

Transformation (cam0):
-----------------------
T_ci:  (imu0 to cam0): 
[[ 0.99920146 -0.03330975 -0.02206602  0.01643918]
 [-0.02221355 -0.00406528 -0.99974498 -0.0176589 ]
 [ 0.03321155  0.99943681 -0.00480196  0.12611205]
 [ 0.          0.          0.          1.        ]]

T_ic:  (cam0 to imu0): 
[[ 0.99920146 -0.02221355  0.03321155 -0.0210067 ]
 [-0.03330975 -0.00406528  0.99943681 -0.12556523]
 [-0.02206602 -0.99974498 -0.00480196 -0.01668606]
 [ 0.          0.          0.          1.        ]]

timeshift cam0 to imu0: [s] (t_imu = t_cam + shift)
0.0

Transformation (cam1):
-----------------------
T_ci:  (imu0 to cam1): 
[[ 0.99725678 -0.02105586  0.07096179 -0.23297074]
 [ 0.07087432 -0.00487226 -0.99747335 -0.02571685]
 [ 0.02134841  0.99976643 -0.00336658  0.12743418]
 [ 0.          0.          0.          1.        ]]

T_ic:  (cam1 to imu0): 
[[ 0.99725678  0.07087432  0.02134841  0.2314338 ]
 [-0.02105586 -0.00487226  0.99976643 -0.13243512]
 [ 0.07096179 -0.99747335 -0.00336658 -0.00869084]
 [ 0.          0.          0.          1.        ]]

timeshift cam1 to imu0: [s] (t_imu = t_cam + shift)
0.0

Baselines:
----------
Baseline (cam0 to cam1): 
[[ 0.99559596 -0.0930107   0.01173568 -0.25246   ]
 [ 0.0929903   0.99566443  0.00227416 -0.00995   ]
 [-0.01189632 -0.00117284  0.99992857  0.001506  ]
 [ 0.          0.          0.          1.        ]]
baseline norm:  0.25266048788 [m]

Gravity vector in target coords: [m/s^2]
[ 9.68080835 -1.50145693 -0.44271849]

Calibration configuration
=========================

cam0
-----
  Camera model: pinhole
  Focal length: [1607.576857, 1606.582234]
  Principal point: [643.371232, 462.113019]
  Distortion model: radtan
  Distortion coefficients: [-0.4017288780460197, 0.1924251840003186, -0.0004990855504208192, -0.0007057831328603431]
  Type: aprilgrid
  Tags: 
    Rows: 6
    Cols: 6
    Size: 0.055 [m]
    Spacing 0.0165 [m]

cam1
-----
  Camera model: pinhole
  Focal length: [1632.338453, 1631.516404]
  Principal point: [645.981571, 485.005055]
  Distortion model: radtan
  Distortion coefficients: [-0.5990205578949735, 0.334083915130278, 0.0003667462903261225, -0.0003914305940027217]
  Type: aprilgrid
  Tags: 
    Rows: 6
    Cols: 6
    Size: 0.055 [m]
    Spacing 0.0165 [m]

**Comment by NikolausDemmel** [comment]
How does the result look when visualizing with `kalibr_visualize_calibration`. Is the visualization somewhat consistent with reality? Is the visualization consistent with the results file?

PS: Your question would be easier to read, if you would format the pasted results as fixed-width font (use triple ``` to format code-blocks).
