### ISSUE TITLE
Stereo Camera Setup

### ISSUE THREAD

**Issue by BirBDey** [ethz-asl/kalibr#173]
Hi,
I am trying to calibrate two USB cameras using Kalibr. I have the calibration files for each of the cameras from "camera_calibration".  I know I can use the ROS and your "kalibr_camera_validator" to calibrate them together but not sure how exactly to do next. Sorry new to Linux and SLAM. 
Any hint will be helpful thanks in advance.
Bikram

**Comment by goldbattle** [comment]
Closing due to age.
