### ISSUE TITLE
Calibrating a monocular VI sensor suite

### ISSUE THREAD

**Issue by SubMishMar** [ethz-asl/kalibr#177]
I am using a monocular camera (oCam-1-CGN-U) and a pixhawk flight controller(FCU) for testing and evaluating SVO2 in my project. I want to know

    How can I use the kalibr tool box to find the Transformation between the FCU and the camera?
    How can I find the imu parameters that need to be specified in the calib files?
    The imu parameters I am interested in are:

imu_params:
delay_imu_cam:
max_imu_delta_t:
acc_max:
omega_max:
sigma_omega_c:
sigma_acc_c:
sigma_omega_bias_c:
sigma_acc_bias_c:
sigma_integration:
g:
imu_rate:

imu_initialization:
velocity:
omega_bias:
acc_bias:
velocity_sigma:
omega_bias_sigma:
acc_bias_sigma:

**Comment by goldbattle** [comment]
Closing due to age.
