### ISSUE TITLE
Monocular Camera IMU calibration 

### ISSUE THREAD

**Issue by SubMishMar** [ethz-asl/kalibr#183]
Can we perform a monocular camera imu calibration using this package? The tutorial given in the wiki is just for stereo imu calibration.

**Comment by NikolausDemmel** [comment]
I guess it should work just the same. Have you tried?

**Comment by SubMishMar** [comment]
Okay! No I havent tried because the tutorial says that I need to send both left and right camera images. I will try and find out then.

**Comment by SubMishMar** [comment]
Yeah it seems to work with a monocular cam+imu setup.. Thanks!

**Comment by SubMishMar** [comment]
In the yaml file for april tags, there are parameters like : 

tagSize: 0.088           #size of apriltag, edge to edge [m]
tagSpacing: 0.3          #ratio of space between tags to tagSize

Does tagSize mean the length of a side of the apriltag?

**Comment by schneith** [comment]
Yes, tagSize should be the length of the tag, edge-to-edge.

**Comment by SubMishMar** [comment]
Cool! Thanks!
