### ISSUE TITLE
Runtime of  cam-imu calibration from source is much longer than CDE package

### ISSUE THREAD

**Issue by zhubaohua** [ethz-asl/kalibr#186]
Hello ,when i take the same cam-imu calibration ,  runtime of cam-imu calibration from source need about 40 minute，however，runtime of cde-package only need  a few minutes. why the  runtime of cam-imu calibration from source is much longer  than CDE package?

**Comment by NikolausDemmel** [comment]
Are you sure you are compiling in release mode (`-DCMAKE_BUILD_TYPE=Release`)?

**Comment by zhubaohua** [comment]
Thanks a lot ,i get it. beside,what is the coordinate system of the camera and IMU in the cam-imu calibration example ,is it the same as the paper:  Unified Temporal and Spatial Calibration for Multi-Sensor Systems?

**Comment by NikolausDemmel** [comment]
Yes, that is in general the reference for cam-imu calibration in kalibr. Not sure what you mean by "what is the coordinate system of the camera and IMU"...

**Comment by zhubaohua** [comment]
what does the color of imu axis mean in figure 1  of  paper "Unified Temporal and Spatial Calibration for Multi-Sensor Systems"？is red represent x axis?

**Comment by NikolausDemmel** [comment]
Jup, usually it is xyz = rgb (red green blue).
