### ISSUE TITLE
parameters ambiguity of aprilgrid.yaml

### ISSUE THREAD

**Issue by panecho** [ethz-asl/kalibr#192]
@kartikmohta @skohlbr @NikolausDemmel @alexmillane 
any detail reference to the parameters in aprilgrid.yaml file, especially the last two. thank you for detail reference.
```
tagSize: 0.088           #size of apriltag, edge to edge [m]
tagSpacing: 0.3          #ratio of space between tags to tagSize
```

**Comment by schneith** [comment]
tagSize is the size of Apriltag; edge to edge [m].
tagSpacing is the (unitless) ratio of space between tags [m] and the tagSize [m] (as defined above)

**Comment by ZhengPan2014** [comment]
@schneith 
just like this?
![image](https://user-images.githubusercontent.com/15884732/41446796-394db404-7084-11e8-8303-1afbc17e03a4.png)

**Comment by schneith** [comment]
yep, that looks correct

**Comment by ZhengPan2014** [comment]
of course, glad about that.
