### ISSUE TITLE
Is it possible to use the library to do extrinsic calibration of two cameras with different resolutions?

### ISSUE THREAD

**Issue by al9ol** [ethz-asl/kalibr#197]
Hello, everyone :)
I have two cameras giving frames of significantly different resolution. Can I use this library to calibrate them (I mean extrinsic calibration first of all)? If Yes, where can I see some code examples?

P.S. I use Python.

Thanks a lot, best regards, algol

**Comment by NikolausDemmel** [comment]
I suggest to read the [documentation](https://github.com/ethz-asl/kalibr/wiki/multiple-camera-calibration). I don't think very different resolution should be a problem.
