### ISSUE TITLE
Camera to Imu calibration results useless

### ISSUE THREAD

**Issue by rikobrandes** [ethz-asl/kalibr#203]
I have such minimally 1m offset in x,y,z direction in the transformation matrix result. I used a 1,4m x 1,4m checkerboard which was positioned in the center of the camera view to avoid (though calibrated) distortions on the test, while moving with 0.05m/s towards the target. Swinging right and left while doing so. 

The camera (1920 x 1208  px) seems to be calibrated fine using kalibr, looking at the indistorted images.

Any ideas?

**Comment by goldbattle** [comment]
Reopen with a bag if this is still an issue.
