### ISSUE TITLE
Allan plot noisy result

### ISSUE THREAD

**Issue by villajuvius** [ethz-asl/kalibr#204]
I made an Allan plot of 4 hours of data capture from my Microstrain 3DM-GX5-45 IMU and the result seems  to be super noisy. Sampling rate is 250Hz. Can you give me feedback from the following result ?

What can cause such noise ?

Thanks

![results_20180706t114938_accel](https://user-images.githubusercontent.com/23116696/42486577-1cafe40c-83fd-11e8-9236-e0ffd8ab93a4.png)
![results_20180706t114938_gyro](https://user-images.githubusercontent.com/23116696/42486579-1ed27f06-83fd-11e8-97b5-da21d74f40b8.png)

**Comment by goldbattle** [comment]
Looks like you need to record a much longer dataset.
