### ISSUE TITLE
Camera IMU calibration: Transformation matrix interpretation

### ISSUE THREAD

**Issue by rikobrandes** [ethz-asl/kalibr#206]
So far i assumed, that the robot is headed in positive x direction towards the calibration target. The positive z axis is pointing up and the positive y axis to the left. Is that right?

**Comment by goldbattle** [comment]
The orientation is pretty arbitrary for the IMU, but should match the one on the sensor platform and be a right-handed one. For the camera the z-axis should be outwards, x-axis to the right and y-axis down if I remember correctly.
