### ISSUE TITLE
Negative baseline 

### ISSUE THREAD

**Issue by roboticists** [ethz-asl/kalibr#207]
Hi
I am performing calibrations using kalibr_calibrate_cameras where the first topic is the left image and the second topic is the right image. The true baseline between left and right cameras is 0.11. The calibrations results produce negative baseline (baseline_0_1 matrix), that is -0.11. The question is how the baseline is calculated and which coordinate frame it follows? Thanks.

**Comment by jiheddachraoui** [comment]
hello,did you ever figure this out?
