### ISSUE TITLE
I made a tutorial video for beginners

### ISSUE THREAD

**Issue by indigomega** [ethz-asl/kalibr#211]
Hey there, as part of my series on YouTube I made a basic tutorial about using Kalibr. I didn’t really know where else to put this so I marked it as a problem (close it when you wish). There are some unrelated comments in the beginning but the rest of the video talks about Kalibr. Please give it a look and if you think it’s good enough I hope you could add it to the wiki. Thanks!

https://m.youtube.com/watch?v=puNXsnrYWTY

**Comment by schneith** [comment]
That's awesome, thanks for sharing your video. I'm sure that this will be very helpful for other trying to use kalibr. I'll add it to the wiki pages.

One small comment about the calibration target: the calibration is quite sensitive to the flatness of target. you might improve the results by using a more flatter target.

**Comment by schneith** [comment]
The video is now linked on the main wiki page. Do you think it makes sense to add it to another section?

**Comment by indigomega** [comment]
Great stuff! Closing now
