### ISSUE TITLE
kalibr_camera_focus Problems with image format

### ISSUE THREAD

**Issue by kauevestena** [ethz-asl/kalibr#214]
After call the script with this command, with a logitech c-270 webcam with 480 x 640 of resolution (the driver is libuvc_camera):

        `kalibr_camera_focus` --topic `/camera/image_raw`

![image](https://user-images.githubusercontent.com/1434036/44290521-7e4ea700-a24f-11e8-8cbb-5bcd64f09057.png)

I just receive the error message that can be seen at the print screen, that is:
> Assertion failed (type == CV_32FC1 || type == CV_32FC2 || type == CV_64FC1 || type == CV_64FC2) in dft

so I opened the code at the `dft` call, and asked for the array sizes, and it outputs `921600` wich is the result of the multiplication `480*640*3` so the script is trying to pass a 3-Band Array to input for the `dft` function.

Checking the documentation here:

> https://docs.opencv.org/3.0-beta/modules/core/doc/operations_on_arrays.html?highlight=dft#cv2.dft

it says that with the `cv2.DFT_COMPLEX_OUTPUT` flag, the function will

>performs a forward transformation of 1D or 2D real array...

EDIT:

in order to make it work for me, i have edited:
```
cv_image = self.bridge.imgmsg_to_cv2(msg)
np_image= np.array(cv_image)
```
for:
```
cv_image = self.bridge.imgmsg_to_cv2(msg)
cv_image = cv2.cvtColor(cv_image,cv2.COLOR_BGR2GRAY)
np_image= np.array(cv_image)
```
e.g explicity converting to single channel image before converting to floating point

Thank you all for this amazing piece of work!

**Comment by AntaresZhang** [comment]
This also solved my problem, Thanks very much!

**Comment by goldbattle** [comment]
Should be fixed. Reopen if this is still an issue for the ROS tools.
