### ISSUE TITLE
wrong result of the calibration of camera and imu.

### ISSUE THREAD

**Issue by ttomchy** [ethz-asl/kalibr#216]
hello,Thanks for providing the algorithm for calibrate the camera ,I am trying to calibrate one camera (pointgrey camera resolution is: 2448*2048) and one IMU (xsens MTI-30-2A5G4).  But I the translation result is apparently wrong. 
I am using the code (https://github.com/rpng/kalibr_allan） to get the imu parameter ,I recorded  about 4 hours' imu data . The following figures shows the imu parameter.
![cap](https://user-images.githubusercontent.com/23189694/44618916-9e1a4680-a8b1-11e8-8ae4-1e3c6ac21764.png)
I use ros message filters (approximate_time) to get synchronized camera and imu topics. I have tried the following code to calibrate the camera and imu.
`kalibr_calibrate_imu_camera --target checkerboard_10x9_45x45cm.yaml  --cam camchain.yaml --imu imu_adis16448.yaml --bag test.bag --show-extraction --time-calibration --bag-from-to 20 140`
Here is the output `importing libraries
Initializing IMUs:
  Update rate: 7
  Accelerometer:
    Noise density: 0.07120086 
    Noise density (discrete): 0.188379768694 
    Random walk: 0.00069865
  Gyroscope:
    Noise density: 0.05389505
    Noise density (discrete): 0.142592899197 
    Random walk: 0.00013758
Initializing imu rosbag dataset reader:
	Dataset:          test.bag
	Topic:            /imu/data
bagstart 1535175681.16
baglength 157.035122156
[ WARN] [1535203375.243458]: BagImuDatasetReader: truncated 261 / 1101 messages.
	Number of messages: 1101
Reading IMU data (/imu/data)
  Read 840 imu readings over 119.8 seconds                   
Initializing calibration target:
  Type: checkerboard
  Rows
    Count: 9
    Distance: 0.045 [m]
  Cols
    Count: 10
    Distance: 0.045 [m]
Initializing camera chain:
Camera chain - cam0:
  Camera model: pinhole
  Focal length: [1817.92373, 1815.088909]
  Principal point: [1233.884, 1018.055]
  Distortion model: equidistant
  Distortion coefficients: [-0.329746, 0.127861, 0.000286, -0.000362]
  baseline: no data available
Initializing camera rosbag dataset reader:
	Dataset:          test.bag
	Topic:            /camera/image_mono
[ WARN] [1535203386.120824]: BagImageDatasetReader: truncated 261 / 1101 images.
	Number of images: 1101
Extracting calibration target corners
  Extracted corners for 823 images (of 840 images)                              

Building the problem
	Spline order: 6
	Pose knots per second: 100
	Do pose motion regularization: False
		xddot translation variance: 1000000.000000
		xddot rotation variance: 100000.000000
	Bias knots per second: 50
	Do bias motion regularization: True
	Blake-Zisserman on reprojection errors -1
	Acceleration Huber width (sigma): -1.000000
	Gyroscope Huber width (sigma): -1.000000
	Do time calibration: True
	Max iterations: 30
	Time offset padding: 0.010000
Estimating time shift camera to imu:

Initializing a pose spline with 11977 knots (100.000000 knots per second over 119.767592 seconds)
  Time shift camera to imu (t_imu = t_cam + shift):
0.0

Estimating imu-camera rotation prior

Initializing a pose spline with 11977 knots (100.000000 knots per second over 119.767592 seconds)
Gravity was intialized to [ 0.39249059 -9.73767693 -1.09179759] [m/s^2]
  Orientation prior camera-imu found as: (T_i_c)
[[ 0.11070178 -0.99384734 -0.00354647]
 [-0.01333265  0.00208301 -0.99990895]
 [ 0.99376424  0.11073898 -0.01302003]]
  Gyro bias prior found as: (b_gyro)
[-0.00139913 -0.0010361  -0.00171439]

Initializing a pose spline with 11981 knots (100.000000 knots per second over 119.807592 seconds)

Initializing the bias splines with 5990 knots

Adding camera error terms (/camera/image_mono)
  Added 823 camera error terms                                

Adding accelerometer error terms (/imu/data)
  Added 840 of 840 accelerometer error terms (skipped 0 out-of-bounds measurements)

Adding gyroscope error terms (/imu/data)
  Added 840 of 840 gyroscope error terms (skipped 0 out-of-bounds measurements)

Before Optimization
===================
Normalized Residuals
----------------------------
Reprojection error (cam0):     mean 4.57556525464, median 3.83019037902, std: 3.14052863551
Gyroscope error (imu0):        mean 0.776189176659, median 0.673089558452, std: 0.46499522126
Accelerometer error (imu0):    mean 8.42534051151, median 7.4356154531, std: 5.1529967451

Residuals
----------------------------
Reprojection error (cam0) [px]:     mean 4.57556525464, median 3.83019037902, std: 3.14052863551
Gyroscope error (imu0) [rad/s]:     mean 0.110679065025, median 0.0959777915591, std: 0.0663050167124
Accelerometer error (imu0) [m/s^2]: mean 1.58716369673, median 1.40071951915, std: 0.970720334923

Optimizing...
Using the block_cholesky linear system solver
Using the levenberg_marquardt trust region policy
Using the block_cholesky linear system solver
Using the levenberg_marquardt trust region policy
Initializing
Optimization problem initialized with 23980 design variables and 72254 error terms
The Jacobian matrix is 146186 x 107895
[0.0]: J: 2.25615e+06
[1]: J: 1.43529e+06, dJ: 820859, deltaX: 0.086054, LM - lambda:10 mu:2
[2]: J: 1.41254e+06, dJ: 22752.6, deltaX: 0.0449414, LM - lambda:3.33333 mu:2
Last step was a regression. Reverting
[3]: J: 1.41304e+06, dJ: -500.698, deltaX: 0.0311119, LM - lambda:1.9283 mu:2
Last step was a regression. Reverting
[4]: J: 1.41295e+06, dJ: -412.411, deltaX: 0.0308121, LM - lambda:7.71321 mu:4
[5]: J: 1.41068e+06, dJ: 1857.34, deltaX: 0.0200523, LM - lambda:61.7056 mu:8
[6]: J: 1.41009e+06, dJ: 587.699, deltaX: 0.00356284, LM - lambda:53.8413 mu:2
[7]: J: 1.41009e+06, dJ: 4.13479, deltaX: 0.00287582, LM - lambda:17.9471 mu:2
[8]: J: 1.41009e+06, dJ: 1.01752, deltaX: 0.00153058, LM - lambda:5.98236 mu:2
[9]: J: 1.41009e+06, dJ: 0.260535, deltaX: 0.00089485, LM - lambda:1.99412 mu:2
[10]: J: 1.41009e+06, dJ: 0.0656521, deltaX: 0.00042174, LM - lambda:0.664707 mu:2
[11]: J: 1.41009e+06, dJ: 0.0215619, deltaX: 0.000262648, LM - lambda:0.221569 mu:2
[12]: J: 1.41009e+06, dJ: 0.00516027, deltaX: 0.000136361, LM - lambda:0.0738563 mu:2

After Optimization (Results)
==================
Normalized Residuals
----------------------------
Reprojection error (cam0):     mean 3.33080798377, median 2.4780331336, std: 2.98102963663
Gyroscope error (imu0):        mean 4.83790927352e-11, median 2.34323703929e-11, std: 1.75644964856e-10
Accelerometer error (imu0):    mean 1.66597981325e-09, median 5.89480753785e-11, std: 1.36866981739e-08

Residuals
----------------------------
Reprojection error (cam0) [px]:     mean 3.33080798377, median 2.4780331336, std: 2.98102963663
Gyroscope error (imu0) [rad/s]:     mean 6.89851509365e-12, median 3.34128962939e-12, std: 2.50457247683e-11
Accelerometer error (imu0) [m/s^2]: mean 3.13836891869e-10, median 1.11046248048e-11, std: 2.57829703619e-09

Transformation T_cam0_imu0 (imu0 to cam0, T_ci): 
[[ 0.11429259 -0.9934421  -0.00316323 -0.00346476]
 [-0.01297465  0.00169114 -0.9999144   0.00089655]
 [ 0.9933624   0.11432385 -0.01269628 -0.00042643]
 [ 0.          0.          0.          1.        ]]

cam0 to imu0 time: [s] (t_imu = t_cam + shift)
0.000174511377104

IMU0:
----------------------------
  Model: calibrated
  Update rate: 7
  Accelerometer:
    Noise density: 0.07120086 
    Noise density (discrete): 0.188379768694 
    Random walk: 0.00069865
  Gyroscope:
    Noise density: 0.05389505
    Noise density (discrete): 0.142592899197 
    Random walk: 0.00013758
  T_i_b
    [[1. 0. 0. 0.]
     [0. 1. 0. 0.]
     [0. 0. 1. 0.]
     [0. 0. 0. 1.]]
  time offset with respect to IMU0: 0.0 [s]

  Saving camera chain calibration to file: camchain-imucam-test.yaml

  Saving imu calibration to file: imu-test.yaml
  Detailed results written to file: results-imucam-test.txt
Generating result report...
/usr/lib/pymodules/python2.7/matplotlib/collections.py:548: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  if self._edgecolors == 'face':
  Report written to report-imucam-test.pdf`

I also tried  with the imu model flag  using the code `
 kalibr_calibrate_imu_camera  --target checkerboard_10x9_45x45cm.yaml  --cam camchain.yaml --imu imu_adis16448.yaml  --imu-models scale-misalignment  --bag test.bag --show-extraction --time-calibration --bag-from-to 20 140`

The following is the output `importing libraries
Initializing IMUs:
  Update rate: 7
  Accelerometer:
    Noise density: 0.07120086 
    Noise density (discrete): 0.188379768694 
    Random walk: 0.00069865
  Gyroscope:
    Noise density: 0.05389505
    Noise density (discrete): 0.142592899197 
    Random walk: 0.00013758
Initializing imu rosbag dataset reader:
	Dataset:          test.bag
	Topic:            /imu/data
bagstart 1535175681.16
baglength 157.035122156
[ WARN] [1535204144.639725]: BagImuDatasetReader: truncated 261 / 1101 messages.
	Number of messages: 1101
Reading IMU data (/imu/data)
  Read 840 imu readings over 119.8 seconds                   
Initializing calibration target:
  Type: checkerboard
  Rows
    Count: 9
    Distance: 0.045 [m]
  Cols
    Count: 10
    Distance: 0.045 [m]
Initializing camera chain:
Camera chain - cam0:
  Camera model: pinhole
  Focal length: [1817.92373, 1815.088909]
  Principal point: [1233.884, 1018.055]
  Distortion model: equidistant
  Distortion coefficients: [-0.329746, 0.127861, 0.000286, -0.000362]
  baseline: no data available
Initializing camera rosbag dataset reader:
	Dataset:          test.bag
	Topic:            /camera/image_mono
[ WARN] [1535204150.497291]: BagImageDatasetReader: truncated 261 / 1101 images.
	Number of images: 1101
Extracting calibration target corners
  Extracted corners for 823 images (of 840 images)                              

Building the problem
	Spline order: 6
	Pose knots per second: 100
	Do pose motion regularization: False
		xddot translation variance: 1000000.000000
		xddot rotation variance: 100000.000000
	Bias knots per second: 50
	Do bias motion regularization: True
	Blake-Zisserman on reprojection errors -1
	Acceleration Huber width (sigma): -1.000000
	Gyroscope Huber width (sigma): -1.000000
	Do time calibration: True
	Max iterations: 30
	Time offset padding: 0.010000
Estimating time shift camera to imu:

Initializing a pose spline with 11977 knots (100.000000 knots per second over 119.767592 seconds)
  Time shift camera to imu (t_imu = t_cam + shift):
0.0

Estimating imu-camera rotation prior

Initializing a pose spline with 11977 knots (100.000000 knots per second over 119.767592 seconds)
Gravity was intialized to [ 0.39249059 -9.73767693 -1.09179759] [m/s^2]
  Orientation prior camera-imu found as: (T_i_c)
[[ 0.11070178 -0.99384734 -0.00354647]
 [-0.01333265  0.00208301 -0.99990895]
 [ 0.99376424  0.11073898 -0.01302003]]
  Gyro bias prior found as: (b_gyro)
[-0.00139913 -0.0010361  -0.00171439]

Initializing a pose spline with 11981 knots (100.000000 knots per second over 119.807592 seconds)

Initializing the bias splines with 5990 knots

Adding camera error terms (/camera/image_mono)
  Added 823 camera error terms                               

Adding accelerometer error terms (/imu/data)
  Added 840 of 840 accelerometer error terms (skipped 0 out-of-bounds measurements)

Adding gyroscope error terms (/imu/data)
  Added 840 of 840 gyroscope error terms (skipped 0 out-of-bounds measurements)

Before Optimization
===================
Normalized Residuals
----------------------------
Reprojection error (cam0):     mean 4.57556525464, median 3.83019037902, std: 3.14052863551
Gyroscope error (imu0):        mean 0.776189176659, median 0.673089558452, std: 0.46499522126
Accelerometer error (imu0):    mean 8.42534051151, median 7.4356154531, std: 5.1529967451

Residuals
----------------------------
Reprojection error (cam0) [px]:     mean 4.57556525464, median 3.83019037902, std: 3.14052863551
Gyroscope error (imu0) [rad/s]:     mean 0.110679065025, median 0.0959777915591, std: 0.0663050167124
Accelerometer error (imu0) [m/s^2]: mean 1.58716369673, median 1.40071951915, std: 0.970720334923

Optimizing...
Using the block_cholesky linear system solver
Using the levenberg_marquardt trust region policy
Using the block_cholesky linear system solver
Using the levenberg_marquardt trust region policy
Initializing
Optimization problem initialized with 23984 design variables and 72254 error terms
The Jacobian matrix is 146186 x 107919
[0.0]: J: 2.25615e+06
[1]: J: 1.43486e+06, dJ: 821285, deltaX: 0.0864867, LM - lambda:10 mu:2
[2]: J: 1.41151e+06, dJ: 23352.3, deltaX: 0.0447415, LM - lambda:3.33333 mu:2
Last step was a regression. Reverting
[3]: J: 1.41207e+06, dJ: -559.262, deltaX: 0.0312542, LM - lambda:1.45585 mu:2
Last step was a regression. Reverting
[4]: J: 1.41204e+06, dJ: -525.8, deltaX: 0.0310841, LM - lambda:5.82341 mu:4
[5]: J: 1.41081e+06, dJ: 703.084, deltaX: 0.0231265, LM - lambda:46.5873 mu:8
[6]: J: 1.41009e+06, dJ: 714.483, deltaX: 0.00710844, LM - lambda:46.6092 mu:2
[7]: J: 1.41009e+06, dJ: 4.99052, deltaX: 0.00302266, LM - lambda:15.5364 mu:2
[8]: J: 1.41009e+06, dJ: 1.15722, deltaX: 0.00181725, LM - lambda:8.51279 mu:2
[9]: J: 1.41009e+06, dJ: 0.330069, deltaX: 0.000997883, LM - lambda:6.63414 mu:2
[10]: J: 1.41009e+06, dJ: 0.0967038, deltaX: 0.000812826, LM - lambda:6.12836 mu:2
[11]: J: 1.41009e+06, dJ: 0.0357911, deltaX: 0.000495062, LM - lambda:6.07863 mu:2
[12]: J: 1.41009e+06, dJ: 0.0110224, deltaX: 0.000394052, LM - lambda:6.06519 mu:2
[13]: J: 1.41009e+06, dJ: 0.00229812, deltaX: 0.000252206, LM - lambda:6.06717 mu:2

After Optimization (Results)
==================
Normalized Residuals
----------------------------
Reprojection error (cam0):     mean 3.3308068414, median 2.47794284678, std: 2.98103091996
Gyroscope error (imu0):        mean 4.61708488215e-07, median 2.39034198282e-07, std: 1.57109714647e-06
Accelerometer error (imu0):    mean 6.67349596491e-09, median 2.70246411637e-09, std: 3.74686490032e-08

Residuals
----------------------------
Reprojection error (cam0) [px]:     mean 3.3308068414, median 2.47794284678, std: 2.98103091996
Gyroscope error (imu0) [rad/s]:     mean 6.58363519186e-08, median 3.40845793404e-08, std: 2.24027297037e-07
Accelerometer error (imu0) [m/s^2]: mean 1.25715162625e-09, median 5.09089565145e-10, std: 7.0583354325e-09

Transformation T_cam0_imu0 (imu0 to cam0, T_ci): 
[[ 0.11429314 -0.99344203 -0.00316565 -0.00346585]
 [-0.01297745  0.00169325 -0.99991436  0.00089637]
 [ 0.9933623   0.11432443 -0.01269882 -0.00042798]
 [ 0.          0.          0.          1.        ]]

cam0 to imu0 time: [s] (t_imu = t_cam + shift)
8.87738126256e-05

IMU0:
----------------------------
  Model: scale-misalignment
  Update rate: 7
  Accelerometer:
    Noise density: 0.07120086 
    Noise density (discrete): 0.188379768694 
    Random walk: 0.00069865
  Gyroscope:
    Noise density: 0.05389505
    Noise density (discrete): 0.142592899197 
    Random walk: 0.00013758
  T_i_b
    [[1. 0. 0. 0.]
     [0. 1. 0. 0.]
     [0. 0. 1. 0.]
     [0. 0. 0. 1.]]
  time offset with respect to IMU0: 0.0 [s]
  Gyroscope: 
    M:
      [[ 0.99979636  0.          0.        ]
       [ 0.00209197  0.99652695  0.        ]
       [-0.00205309  0.00092927  0.99736881]]
    A [(rad/s)/(m/s^2)]:
      [[ 0.00154999 -0.00001688  0.00093119]
       [-0.00637655 -0.0051548  -0.00255806]
       [-0.00015744 -0.00028733 -0.00027278]]
    C_gyro_i:
      [[ 0.99999771 -0.00169169  0.00131341]
       [ 0.00169353  0.99999759 -0.00139933]
       [-0.00131104  0.00140155  0.99999816]]
  Accelerometer: 
    M:
      [[ 1.00028102  0.          0.        ]
       [-0.00025133  1.00224152  0.        ]
       [ 0.00036224  0.00199759  1.00057533]]

  Saving camera chain calibration to file: camchain-imucam-test.yaml

  Saving imu calibration to file: imu-test.yaml
  Detailed results written to file: results-imucam-test.txt
Generating result report...
/usr/lib/pymodules/python2.7/matplotlib/collections.py:548: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  if self._edgecolors == 'face':
  Report written to report-imucam-test.pdf

`

However It seems that the result is almost the same (both are wrong result.) is anyone can help me ?

**Comment by RuanJiaJun** [comment]
I also encountered this problem. Have you solved it now? Can you share the solution? Thank you！

**Comment by goldbattle** [comment]
Closing due to age.
