### ISSUE TITLE
Performing an IMU to known reference calibration without a camera

### ISSUE THREAD

**Issue by yotamat** [ethz-asl/kalibr#217]
Hi,

I am calibrating an IMU relative to a known reference marker on a rig, which is already tracked by an external system.  I have time synchronized outputs from the IMU gyro, accelerometer and the pose of the marker, and I would like to utilize Kalibr to find the relative location and orientation of the IMU and the reference.

I know Kalibr normally extracts the motion of the camera reference frame by analyzing video of a calibration pattern captured while the rig is moved in front of the pattern, and then performs the relative (IMU-Camera) calibration. Is there an option to easily bypass the video analysis of the egomotion of the camera, and instead input an external motion signal?

Any input or pointer in the right direction would be appreciated!
Cheers

**Comment by goldbattle** [comment]
This package doesn't perform this (only camera to IMU transform).
You can checkout this package if you still require this:
https://github.com/rpng/vicon2gt
