### ISSUE TITLE
Kalibr- RealSense-ArduCopter

### ISSUE THREAD

**Issue by aet2230** [ethz-asl/kalibr#224]
Hi!
I try to perform "kalibration" to RealSense camera to Pixhawk IMU with ArduCopter. 
The calibration runs and I get transformation matrix that makes sense, for example 
T_ic:  (cam0 to imu): [m]
[[ 0.18566984 -0.01567314  0.98248718 -0.00074275]
 [-0.98079541  0.05781811  0.18627247  0.00028997]
 [-0.05972502 -0.9982041  -0.00463706 -0.00246395]
 [ 0.          0.          0.          1.        ]]
but I immediately see that the right (displacements) column is wrong (on my setup I have about 10 cm displacements on x and z axes);
Also when I test the transformation, I get large errors (about 40 cm on each axis). I've tried multiple parameters(suc as noise and changing target from checkerboard to aprilgrid) but the results are similar.

The only thing I can think about is that the IMU data flow via MAVlink is at 1[Hz]. As I know, there is no possibility ti increase the rate above 4Hz when using ArduCopter.

May this be a problem? Did anybody deal with it? If not - what may be the problem?
Thanks

**Comment by ZacharyTaylor** [comment]
The IMU rate is almost certainly the issue. If insufficient information is given to the solver it will typically give an output near 0. I have noticed this tendency occurring on low data rate or overly damped IMUs before. Going to 4 Hz won't help much, I would expect you need at least 50 Hz+ for reliable estimation.

I have not used ArduCopter before, but make significant use of PX4 which runs on the exact same hardware, and this is able to reliably output the IMU up to rates of 250 Hz, so I would be surprised if ArduCopter can't output at the needed speeds.
