### ISSUE TITLE
A Question on the Output File of Multiple camera calibration

### ISSUE THREAD

**Issue by Ethan-Zhou** [ethz-asl/kalibr#225]
Hi, I run the sample of Multiple camera calibration, which returns me a pdf file. My question is regarding the first page, which illustrates an observation graph. Could you please explain how this graph is constructed? How to determine which edges are important. It seems to me that a minimum spanning tree is determined here, but the weight being selected is neither minimum nor maximum. I cannot see discussion/explaination on this in the reference paper by the way.
Many thx;)

**Comment by goldbattle** [comment]
This graph is pretty arbitrary. The yaml files can be used with the topics to reconstruct any desired relative transformation.
