### ISSUE TITLE
Calibration of a 250deg fisheye lens

### ISSUE THREAD

**Issue by caselitz** [ethz-asl/kalibr#242]
Hi all,

my goal is to find a suitable camera model for the [Entaniya Fisheye M12 250](http://products.entaniya.co.jp/products/m12-fisheye/entaniya-fisheye-m12-specification/) lens and calibrate it.

My first attempt was to go for the Double Sphere `ds_none` model [recently contributed to Kalibr](https://github.com/ethz-asl/kalibr/pull/210) (thanks!).

@NikolausDemmel and @VladyslavUsenko, in your paper you experimented with multiple wide-angle/fish-eye lenses and showed that the model performed well, however the lens with the biggest FOV was the `BF2M2020S23` with 195deg. What's your intuition about a 250deg lens - do you think the model can properly describe it? Or would you recommend a different model available in Kalibr?

I could provide a calibration sequence of my lens in case you are willing to experiment with it (maybe also interesting for future publication?).

Anyhow, maybe even multiple camera models are suited. The actual problem regarding calibration seems to be the point Niko raised [here](https://github.com/ethz-asl/kalibr/pull/210#discussion_r209276503). When I try to calibrate my lens, the majority of points gets removed because of the 80deg check (or actually the use of _pinhole-undistored 2d corrdinates_ instead of _bearing-vectors_).

It seems that the loss of `195/2-80=17.5deg` was acceptable for you to still fit an accurate model, but maybe `250/2-80=45deg` is to much - what do you think? With most of the calibration sequences I tried Kalibr failed, probably due to the removal of so many points. However, one sequence actually worked but I don't expect the results to be very precise (have to investigate further), at least for the outer parts of the image as used keypoints where only in a quite small inner circle area of the image space.

As Niko said, _the proper fix would be to use a PNP implementation that allows to give bearing-vectors as input and not pinhole-undistored 2d corrdinates._ I guess no one is planning to take any action in the near future here? ;-) Unfortunately, I feel my knowledge of the Kalibr code is a bit limited to do that, but in case I wanna give it a try, can anyone give me an idea what has to be done?

From what I understand, the [estimateTransformation function](https://github.com/ethz-asl/kalibr/blob/master/aslam_cv/aslam_cameras/include/aslam/cameras/implementation/OmniProjection.hpp#L871) needs to be changed to use all points to solve the PNP problem. I see 2 sub-tasks here:
1. Getting the bearing vectors
2. Use a PNP solver that takes in bearing vectors

For 1: Using `keypointToEuclidean()` I get a 3D point (with possibly negative z) that can be used to compute the bearing vector. Straight forward?
For 2: Where to get such a solver? Niko mentioned [OpenGV](https://github.com/laurentkneip/opengv). I'm not sure how easy and desirable the use of an external library in Kalibr is? (However, for my own purposes I can just try to hack it in, if it's not too complicated. Any hints how to do this?). Probably a re-implementation of such a PNP solver in Kalibr would be considerable effort?

Any help is greatly appreciated, thanks! :-)
Best, Tim

**Comment by VladyslavUsenko** [comment]
Hi Tim,

Yes, it would be nice if you could provide a dataset with your lens. The PnP problem is used only for initialization of the camera pose, but after that all observations (even larger than 80 degrees) should be used for optimization.

As you mentioned, the proper solution would be to use OpenGV with bearing vectors, but I'm not sure if we should add new dependencies for kalibr. An alternative could be to uses several (virtual) rotated pinhole cameras for pose initialization. This way it would be possible to use the same OpenCV function as used now. 

Best,
Vlad

**Comment by caselitz** [comment]
> Yes, it would be nice if you could provide a dataset with your lens.

Ok, cool. I'll follow up on this.

> The PnP problem is used only for initialization of the camera pose, but after that all observations (even larger than 80 degrees) should be used for optimization.

Thanks for clarifying this! Then this is probably not so crucial, at least for the quality of the resulting calibration? But I guess, this assumes the optimization is still properly converging (to a not-too-bad local minimum). And proper initial pose estimates (obtained by solving PNP) are actually important to make such a (non-convex NLLS) problem properly converge, right?

That all observations are used is because the variable `success` in [this line](https://github.com/ethz-asl/kalibr/blob/master/aslam_offline_calibration/kalibr/python/kalibr_camera_calibration/CameraIntializers.py#L220) is kinda ignored and all `obs` are added to the `problem`? For the non-success case, I actually wonder which value the initial pose `T_t_c` has as `out_T_t_c` is not written in [estimateTransform()](https://github.com/ethz-asl/kalibr/blob/master/aslam_cv/aslam_cameras/include/aslam/cameras/implementation/OmniProjection.hpp#L871) (is that somewhere hidden in the Python C++ wrapping?).

> all observations (even larger than 80 degrees) should be used for optimization.

Actually, this does not fit my experience, but admittedly N is only 1 ;) - as I said in my last post, one sequence "worked", but the report showed only reprojection errors for in the inner part of the image, which would say the outer ones were not used, right?

So, from a practical point of view, I need to ensure good enough initialization to make the optimization converge. Any hints on how to do that?

1. I guess I should make sure to have enough pictures in the sequence that are in the center part of the image and can have a proper initial pose estimate (obtained by solving PNP)?
2. Niko said that _also how initialization is done (starting optimization with a single image and consecutively adding more)_ matters. [Why is this? If i read [calibrateIntrinsics()](https://github.com/ethz-asl/kalibr/blob/master/aslam_offline_calibration/kalibr/python/kalibr_camera_calibration/CameraIntializers.py#L188) correctly, first all error terms of all obervations are added, then it is optimized. Or am I on the wrong page here?] If that is the case, any recommendations how to record a calibration sequence (sth like first target in the center than on the sides)?

> As you mentioned, the proper solution would be to use OpenGV with bearing vectors, but I'm not sure if we should add new dependencies for kalibr. An alternative could be to uses several (virtual) rotated pinhole cameras for pose initialization. This way it would be possible to use the same OpenCV function as used now.

Understand with the dependencies. That's why an own kalibr re-implementation could be a way to go. I like your idea with the multiple pinhole, however I still feel the bearing vectors would be the best solution. But probably much effort, I guess more than the multiple pinholes idea?

Thank for you quick reply Vlad!

Best,
Tim

**Comment by caselitz** [comment]
> Niko said that also how initialization is done (starting optimization with a single image and consecutively adding more) matters. [Why is this? If i read calibrateIntrinsics() correctly, first all error terms of all obervations are added, then it is optimized. Or am I on the wrong page here?] If that is the case, any recommendations how to record a calibration sequence (sth like first target in the center than on the sides)?

I should probably read the whole code from the beginning once. I guess you referred to the [main function](https://github.com/ethz-asl/kalibr/blob/master/aslam_offline_calibration/kalibr/python/kalibr_calibrate_cameras#L140) where it is [looped over the views](https://github.com/ethz-asl/kalibr/blob/master/aslam_offline_calibration/kalibr/python/kalibr_calibrate_cameras#L264)? From here it makes sense that the order has influence, also as the [views (potentially) get shuffled](https://github.com/ethz-asl/kalibr/blob/master/aslam_offline_calibration/kalibr/python/kalibr_calibrate_cameras#L255). Question would still be if there is a good order to choose while recording (and using the `--no-shuffle` option).

**Comment by caselitz** [comment]
> > Yes, it would be nice if you could provide a dataset with your lens.
> 
> Ok, cool. I'll follow up on this.

Finally I found the time to record some (11) bag files that you can [download here](http://www2.informatik.uni-freiburg.de/~caselitz/downloads/calib_data/).

@VladyslavUsenko, @NikolausDemmel: Would appreciate if you share any findings/thoughts in case you have a look at the data.

Thanks and happy XMas,
Tim

**Comment by VladyslavUsenko** [comment]
Hi Tim,

Sorry, but we didn't really had time to check this issue in Kalibr. We've recently open-sourced our internal calibration tool (https://gitlab.com/VladyslavUsenko/basalt) and there it seems to work.

![250_deg](https://user-images.githubusercontent.com/2621267/56213473-60467a00-605c-11e9-8ddb-a949c61fa639.png)

The command I used is:
```
basalt_calibrate --dataset-path bag02.bag --dataset-type bag --result-path calib_result --cam-types eucm
```
You can give it a try if you still need to calibrate the lens.

Best,
Vlad

**Comment by caselitz** [comment]
Hey Vlad (and Niko),

thanks for the update, great work! I'll let you know once I find the time...

Best,
Tim
