### ISSUE TITLE
Calibrate IMU only. 

### ISSUE THREAD

**Issue by funmonty** [ethz-asl/kalibr#252]
I am in need of calibrating IMU only. Is it possible to calibrate only IMU sensor without camera data using kalibr? If yes, can you please suggest how? I would also like to know if there are any standard ways to calculate the misalignment matrix, scale matrix, etc. And any recommendations using other sources are also welcome. Thanks in advance.

**Comment by IrisGreen** [comment]
Maybe you can have a look at kalibr_allan , imu_tk or imu_utils, you can easily get them on github: )

**Comment by goldbattle** [comment]
See issue https://github.com/ethz-asl/kalibr/issues/76
