### ISSUE TITLE
How the est. bodyspline work?

### ISSUE THREAD

**Issue by LeungHEX** [ethz-asl/kalibr#254]
Since I use the CAM-IMU in the CDE tool, the result comes out that the est. bodyspline is quite dismatch with the true imu data. And here comes the question, how the body spline estimated? it's not that resonable that the error has come to the height of 6.0*10e6. Seems a bit ridiculous for the real imu. How can I improve it? Maybe the data should be re-sampled?

**Comment by goldbattle** [comment]
Please provide more concrete details and a dataset. Likely your noise values are incorrect.
