### ISSUE TITLE
should use same pattern size for findChessboardCorners() and drawChessboardCorners()

### ISSUE THREAD

**Issue by vanurag** [ethz-asl/kalibr#27]
[findChessboardCorners](https://github.com/ethz-asl/kalibr/blob/master/aslam_cv/aslam_cameras/src/GridCalibrationTargetCheckerboard.cpp#L92) uses cv::Size patternSize(cols(), rows());

but [drawChessboardCorners](https://github.com/ethz-asl/kalibr/blob/master/aslam_cv/aslam_cameras/src/GridCalibrationTargetCheckerboard.cpp#L106) uses cv::Size(rows(), cols())

This causes wrong drawing of chessboard corners with different colors in same line like this:
![selection_013](https://cloud.githubusercontent.com/assets/7656222/8358457/8dff3f4e-1b60-11e5-900c-390c33a5e964.png)

instead of this:
![selection_012](https://cloud.githubusercontent.com/assets/7656222/8358461/922e6518-1b60-11e5-9148-40387763d1f8.png)

**Comment by omaris** [comment]
Can you fix this in a pr?

**Comment by vanurag** [comment]
sure!
