### ISSUE TITLE
error for kalibr_calibrate_rs_cameras

### ISSUE THREAD

**Issue by mysunnyday** [ethz-asl/kalibr#278]
I'm trying to calib an android camera. I sample the image with 30Hz and AE model. run the command by 

kalibr_calibrate_rs_cameras --model pinhole-radtan-rs --target april_6x6.yaml --topic /cam0/image_raw --bag cam0s5.bag --inverse-feature-variance 1 --frame-rate 30

than got the error ,  any advice ? :)

> importing libraries
> 	Dataset:          cam0s5.bag
> 	Topic:            /cam0/image_raw
> 	Number of images: 1668
> Extracting calibration target corners
>   Extracted corners for 1663 images (of 1668 images)                              
> 
> Initializing a pose spline with 589 knots (100.000000 knots per second over 58.882753 seconds)
> run new optimisation with initial values:
> 
> LineDelay:
> 6.94444444444e-05
> Intrinsics:
> [ 1561.50286788  1561.50286788   319.5          239.5       ]
> Distortion:
> [ 0.  0.  0.  0.]
> Using the block_cholesky linear system solver
> Using the dog_leg trust region policy
> Using the block_cholesky linear system solver
> Using the dog_leg trust region policy
> Initializing
> Optimization problem initialized with 595 design variables and 197695 error terms
> The Jacobian matrix is 395389 x 3561
> [0.0]: J: 9.52322e+08
> Exception in thread block: [aslam::Exception] /home/grw/kalibr_workspace/src/Kalibr/aslam_nonparametric_estimation/aslam_splines/src/BSplineExpressions.cpp:447: toTransformationMatrixImplementation() assert(_bufferTmin <= _time.toScalar() < _bufferTmax) failed [515134 <= 515134 < 515134]: Spline Coefficient Buffer Exceeded. Set larger buffer margins!
> Exception in thread block: [aslam::Exception] /home/grw/kalibr_workspace/src/Kalibr/aslam_nonparametric_estimation/aslam_splines/src/BSplineExpressions.cpp:447: toTransformationMatrixImplementation() assert(_bufferTmin <= _time.toScalar() < _bufferTmax) failed [515147 <= 515148 < 515148]: Spline Coefficient Buffer Exceeded. Set larger buffer margins!
> Exception in thread block: [aslam::Exception] /home/grw/kalibr_workspace/src/Kalibr/aslam_nonparametric_estimation/aslam_splines/src/BSplineExpressions.cpp:447: toTransformationMatrixImplementation() assert(_bufferTmin <= _time.toScalar() < _bufferTmax) failed [515164 <= 515164 < 515164]: Spline Coefficient Buffer Exceeded. Set larger buffer margins!
> Exception in thread block: [aslam::Exception] /home/grw/kalibr_workspace/src/Kalibr/aslam_nonparametric_estimation/aslam_splines/src/BSplineExpressions.cpp:447: toTransformationMatrixImplementation() assert(_bufferTmin <= _time.toScalar() < _bufferTmax) failed [515177 <= 515178 < 515178]: Spline Coefficient Buffer Exceeded. Set larger buffer margins!
> [ERROR] [1556532792.241193]: Exception: std::exception

**Comment by mysunnyday** [comment]
it seems some error about time stamp, I write the image to sdcard in the ndk camera2 callback function. but I found the timestamp is not stable, most stamp gap between sequence frame is 33ms , but sometime it could be 66ms or 99ms, I don't know if this situation would broken the optimizer ?

**Comment by mysunnyday** [comment]
and in the ndk code , I have set the ACAMERA_CONTROL_AE_TARGET_FPS_RANGE to 30 then get 30fps , 
and in the callback func I can get ACAMERA_SENSOR_ROLLING_SHUTTER_SKEW as 33ms , and ACAMERA_SENSOR_EXPOSURE_TIME around 9ms ~ 29ms in different light condition.  so what's the relationship between exposure time, rolling sutter time, and frame rate and line delay? have I used the right camera configuration ?

**Comment by mysunnyday** [comment]
anyway , use the non-rs method like 
kalibr_calibrate_cameras --target april_6x6.yaml --bag cam0s2_sample.bag --models pinhole-radtan --topics /cam0/image_raw

always return a result, although the re-proj error is bounded in 1pix, I think it's not good enough, I'd like to try the rolling edition for improvement

**Comment by goldbattle** [comment]
For others that run into this issue, I would recommend you checkout the pr https://github.com/ethz-asl/kalibr/pull/261 if you have not already.

**Comment by SjjAugust** [comment]
I have the same problem. Did you figure out it ?

**Comment by goldbattle** [comment]
@SjjAugust have you tried pr #261?

**Comment by SjjAugust** [comment]
> @SjjAugust have you tried pr #261?

Yes, I follow pr # 261, here is my operation
1. Keep the camera still, move the target quickly, record a 40-second video (30hz)
2. Get each frame of the video and timestamp it
3. Create a bag using bagcreater
4. Use the following script to calibrate `python kalibr_calibrate_rs_cameras \
--model pinhole-equi-rs --target april_6x6_80x80cm.yaml \
--topic / cam0 / image_raw \
--inverse-feature-variance 1 --frame-rate 30 `
After extracting the corner points of all pictures, a problem occurred: `list index out of range`
I don't know what went wrong, hope to get help, thanks.

**Comment by goldbattle** [comment]
Did you checkout the PR branch? or just the master in this repository?
```
git fetch origin pull/261/head:pr_261
git checkout pr_261
git log -1 <- should have commit from that pr
```
You should be able to run it with rosrun after rebuilding in your workspace.

**Comment by SjjAugust** [comment]
> Did you checkout the PR branch? or just the master in this repository?
> 
> ```
> git clone https://github.com/ethz-asl/kalibr/
> cd kalibr
> git fetch origin pull/261/head:pr_261
> git checkout pr_261
> git log -1 <- should have commit from that pr
> ```
> 
> You should be able to run it with rosrun after rebuilding in your workspace.

Thank you very much, I can run smoothly after changing the branch, here are my results:
LineDelay:
3.08641975309e-05
Intrinsics:
[ 2553.76736216  2553.76736216   959.5          539.5       ]
Distortion:
[ 0.  0.  0.  0.]
Using the block_cholesky linear system solver
Using the dog_leg trust region policy
Using the block_cholesky linear system solver
Using the dog_leg trust region policy
Initializing
Optimization problem initialized with 428480 design variables and 9039 error terms
The Jacobian matrix is 18077 x 2570871
[0.0]: J: 86229.5

I still have two questions:
1. I use 30hz to shoot 1080p video, but the obtained linedelay is exactly equal to 1 / (30 * 1080). Does this prove that the selected picture has not been skewed during calculation? I check every frame of the video. I found that the skewed pictures are blurry. Is it related to this?
2. After getting the above results, the console is stuck. Does this indicate that the calculation has been completed? Is this normal?

**Comment by goldbattle** [comment]
What is printed should be the initial guess. It should optimize for quite some time, and that first `J:` printout is just before it starts doing the first iteration if my memory is correct. It also has a knot refinement stage also which means it takes 2x as long to do just the first problem.

**Comment by goldbattle** [comment]
Feel free to reopen with a bag to reproduce any problems.
