### ISSUE TITLE
What's the meaning of ‘T_ci: (imu0 to cam0)

### ISSUE THREAD

**Issue by shilei001** [ethz-asl/kalibr#280]
I  don't understand the every value of 4*4matrix T_ci means.
I know it's rotation matrix  which contain 3*3 matrix ,equival with Eular angle，and distance in Vector（xyz，under imu frame or cam frame）.
If anybody could help ,it would be gald, thank you.

Transformation (cam0):
-----------------------
T_ci: (imu0 to cam0):
[[-0.00178254 0.99988302 -0.01519097 0.05477101]
[-0.9999971 -0.00180694 -0.00159266 -0.00577582]
[-0.00161993 0.01518809 0.9998

**Comment by goldbattle** [comment]
The top rotation will be the rotation from the IMU to the CAM (R_ItoC).
The translation will be the IMU int the CAM frame (p_IinC).
http://ingmec.ual.es/~jlblanco/papers/jlblanco2010geometry3D_techrep.pdf

![image](https://user-images.githubusercontent.com/2222562/67014942-b0fa6680-f0c3-11e9-8973-b6e644ed6352.png)
