### ISSUE TITLE
Did not coverge in maxIterations - Multicam Calibration

### ISSUE THREAD

**Issue by arjunds** [ethz-asl/kalibr#288]
![screenshot1](https://user-images.githubusercontent.com/17018487/59812752-ec2a8b80-92c3-11e9-9455-9621483a80d3.png)
![screenshot2](https://user-images.githubusercontent.com/17018487/59812754-ecc32200-92c3-11e9-8276-ecde33b5209f.png)

So for some reason when I try to calibrate my depth and stereo cameras together, it fails, but when I do each of them separately, it works perfectly fine. Attached are screenshots for what happens when I try to calibrate it together. I have tried increase the maxIterations value from 50 all the way up to 500, but still with no luck.

Anyone have this issue?

**Comment by Current-River** [comment]
excuse me,I have the same problem.have you solved it?

**Comment by arjunds** [comment]
The only solution I found was to use IMU-Camera calibration and that yielded better results.

**Comment by liumingzs** [comment]
I move the d435i camera slowly and avoid turn the camera big degree
