### ISSUE TITLE
No error for imu on camera_imu_calibration

### ISSUE THREAD

**Issue by jakemclaughlin6** [ethz-asl/kalibr#292]
I am attempting to create a synchronized camera and imu sensor for use with SLAM. Currently timestamping for the camera is done on an arduino which is synced with the computer time at 20Hz. The IMU samples at roughly 30Hz and is timestamped on the computer. After running the camera imu calibration, the transformation between the frames is not correct, and the IMU shows 0 error in its measurements which I find very odd. I'm not altering the UM7 timestamping in any way since the arduino is well synchronized to the PC clock so both image timestamps and IMU timestamps should be stamped in the same clock, I'm not sure if this is a correct assumption or not.

Here are the results: 
[report-imucam-calib.pdf](https://github.com/ethz-asl/kalibr/files/3378797/report-imucam-calib.pdf) 

And here are the input files: 
[camchain-calib.txt](https://github.com/ethz-asl/kalibr/files/3378802/camchain-calib.txt)
[imu.txt](https://github.com/ethz-asl/kalibr/files/3378804/imu.txt)
[target.txt](https://github.com/ethz-asl/kalibr/files/3378809/target.txt)

The camera being used is a FLIR blackfly, and the IMU is a CH-UM7.

**Comment by HankDa** [comment]
Hi, I'm have same problem with IMU error and I try to arise the IMU ODR to 200hz, that solve the problem.
