### ISSUE TITLE
What does the "image index" mean?

### ISSUE THREAD

**Issue by EmiyaEstelle** [ethz-asl/kalibr#303]
Hi
Recently I have been using the Kalibr to do the imu-cam calibration. I have got a result (you can see it in the below picture)
![image](https://user-images.githubusercontent.com/24841373/65829622-e50b1480-e2d9-11e9-952a-4c205cf623ec.png)
So what meanings of "image index" is it? Waht meanings does the value of this index have?
Thank you

**Comment by goldbattle** [comment]
My understanding is that image index should correspond to the images collected through the dataset.
So zero would be the start of the dataset, with larger ones being towards the end.
Note that there is frame selection, so it is not a 1-to-1 with the images in the rosbag normally.

**Comment by EmiyaEstelle** [comment]
Thanks for your answer @goldbattle 
You mean that it is aussmed that I collect 100 pictures from a camera. But actually no every picture is good for kalibr or that is to say that kalibr will choose the appropriate picture in a rosbag. So the image index is the one which are choosen.
