### ISSUE TITLE
Continuous-Time Approach vs Imu Preintegration

### ISSUE THREAD

**Issue by mmmfarrell** [ethz-asl/kalibr#307]
Hey guys! Thanks for your work on kalibr. I think this is a great tool that is very useful to any roboticist. 

I recently read through your paper "Continous-Time Batch Estimation using Temporal Basis Functions" and had a question. I understand the very important contribution of deriving a continuous-time formulation for the MLE problem, however, my question more specifically refers to the problem of self-calibration of the transform between an IMU and a camera. This is one of the problems that kalibr solves and is also the problem used to demonstrate the effectiveness of the continuous-time formulation in the paper.

In the past few years, many visual-inertial estimation methods have made use of IMU preintegration (see ["On-Manifold Preintegration for Real-Time Visual-Inertial Odometry"](http://rpg.ifi.uzh.ch/docs/TRO16_forster.pdf)). In your paper, one of the main points is that by using the continous-time approach one does not have to estimate the state variables at the time of each measurement (IMU or camera). This is also possible, however, by using preintegrated IMU. With preintegrated IMU, you can simply estimate the state variables at the time of each camera image and use the imu preintegration to inform about the relative motion from one image to the next. My question is, does the continous-time approach have significant benefit over an approach using IMU preintegration? 

Do you feel that kalibr performs better due to the continous-time approach than a similar approach using IMU preintegration? If so, why?

Thanks for your time considering my question. Please, anyone feel free to pitch in with your thoughts and understanding of this topic. Thank you!

**Comment by goldbattle** [comment]
One of the challenges of IMU preintegration is that you need to isolate the measurements from the state. If you are doing calibration this is much harder and normally require approximations (i.e. the expansion of bias about the linearization point is an example of this). With continuous time one doesn't have to split the trajectory into sections and instead and write each interval measurement as a direct function of the derivatives of our basis functions, thus would lead for less approximations at the cost of speed.

**Comment by kannidekan** [comment]
execuse me, do you know how could i get the IMU YAML file of the requirements in the camera-imu calibration? #341

Thanks very much!
