### ISSUE TITLE
Camera-camera reprojection error.

### ISSUE THREAD

**Issue by alejandronespereira** [ethz-asl/kalibr#323]
How can I see the reprojection error between cameras? 

Say cameras 1 and 2 have detected a corner C, is there any measure for the error of C detected in cam1 being projected to cam2?

**Comment by kannidekan** [comment]
execuse me, do you know how could i get the IMU YAML file of the requirements in the camera-imu calibration? #341

Thanks very much!

**Comment by goldbattle** [comment]
For reprojection error, you need the 3d position of the feature. Thus it makes more sense to ask what the reprojection error of the board into the current frame (this what is reported in the console).
