### ISSUE TITLE
kalibr_calibrate_cameras  ... --show-extraction failed

### ISSUE THREAD

**Issue by jyzhong** [ethz-asl/kalibr#325]
with --show -extraction . I got "Attempt to unlock mutex that was not locked". Without it, kalibr_calibrate_cameras works.

**Comment by frme92** [comment]
I have the same problem, someone can fix this?

**Comment by kannidekan** [comment]
execuse me, do you know how could i get the IMU YAML file of the requirements in the camera-imu calibration? #341

Thanks very much!

**Comment by jyzhong** [comment]
> execuse me, do you know how could i get the IMU YAML file of the requirements in the camera-imu calibration? #341
> 
> Thanks very much!

use the tool "kalibr_allan"

**Comment by jyzhong** [comment]
try to replace "cvStartWindowThread()" with "cv::waitKey(1)",  it will fix this issue.

**Comment by Xiangyf18** [comment]
> try to replace "cvStartWindowThread()" with "cv::waitKey(1)", it will fix this issue.
Thanks a lot  for your suggestion ,it really works. 
 Exactly I change  this file : 
 {my_Kalibr_source_code_path}/aslam_cv/aslam_cameras/src/GridCalibrationTargetCheckerboard.cpp

**Comment by AntarcticaSkj** [comment]
> 

Thank U! It help me a lot !

**Comment by AntarcticaSkj** [comment]
> Thanks a lot for your suggestion ,it really works. Exactly I change this file : {my_Kalibr_source_code_path}/aslam_cv/aslam_cameras/src/GridCalibrationTargetCheckerboard.cpp
> 
> > try to replace "cvStartWindowThread()" with "cv::waitKey(1)", it will fix this issue.

Thank U! It help me a lot !
