### ISSUE TITLE
Two Pointgrey Camera Calibration

### ISSUE THREAD

**Issue by meihouking** [ethz-asl/kalibr#337]
![eyeCamera-00L](https://user-images.githubusercontent.com/20368577/71439856-1a3acd80-2736-11ea-9a30-aec0f457374a.jpg)
![eyeCamera-00R](https://user-images.githubusercontent.com/20368577/71439858-1ad36400-2736-11ea-8ddd-15152643b88a.jpg)
I try to use Kalibr to calibrate two pointgrey Camera. These images almost have no distortion. The distance of two cameras is x=6.4~6.7cm , Y= Close to 0, Z= Close to 0. but the result is wrong.
 Cam resolution: [1920, 1200], Cam model : pinhole-fov
I dont know what problem cause the result wrong?

**Comment by kannidekan** [comment]
execuse me, do you know how could i get the IMU YAML file of the requirements in the camera-imu calibration? #341 

Thanks very much!

**Comment by goldbattle** [comment]
FOV is normally used for fisheye cameras which you don't seem to have. I recommend you try the other distortion models. Please provide a bag where you have issues running / expand the exact problem you have, thanks!
