### ISSUE TITLE
Optimization failed

### ISSUE THREAD

**Issue by noobslamer** [ethz-asl/kalibr#338]

**Comment by kannidekan** [comment]
execuse me, do you know how could i get the IMU YAML file of the requirements in the camera-imu calibration? #341 

Thanks very much!

**Comment by Qin-Sir** [comment]
@ @kannidekan this may will help you
https://github.com/gaowenliang/imu_utils

**Comment by noobslamer** [comment]
你好，我已收到邮件，必尽快回复
