### ISSUE TITLE
No corners could be extracted for low resolution images( confidence image )

### ISSUE THREAD

**Issue by arenas7307979** [ethz-asl/kalibr#344]
I am trying to calibrate a tof camera（TI TINTIN)

the problem is that for every dataset  I always receive the error
[FATAL] [1572255263.563560]: No corners could be extracted for ...

the image below.
![1579229142506541000](https://user-images.githubusercontent.com/5019568/72592699-14ec2f80-393e-11ea-99d1-63c5b32c2f34.png)

**Comment by sebasantibanez** [comment]
Hi @arenas7307979, I'm in the same boat.  Did you manage to solve it?

**Comment by arenas7307979** [comment]
I think it has something problem from the sharpness of the april_calibration image, which leads to the lack of feature points,  maybe u can using general chessboard to calibration

**Comment by goldbattle** [comment]
I think tuning the camera parameters or doing some preprocessing will be necessary to have enough gradient for detection. If you do find a solution, feel free to post for others to see. Additionally, posting a bag would help others debug.

**Comment by tejalbarnwal** [comment]
hey, it might be possible that the images are mirrored. Please check for the same
