### ISSUE TITLE
Intrinsics change when new cameras are added

### ISSUE THREAD

**Issue by SubMishMar** [ethz-asl/kalibr#348]
While using Kalibr for multi-camera calibration, I made the following observations.
1. When I was using just 2 cameras (Cam_0 and Cam_1), I got intrinsics as (K_0, D_0) & (K_1, D_1) and the extrinsic as T^(1)_{0}. (These two cameras come as stereo pairs and their stereo calibration is known, I compare it with T^(1)_{0} and the found the estimation to be as good as the factory calibration)
2. I added a third camera (Cam_2) and calibrated the entire setup again. This time I got different intrinsics for Cam_0 and Cam_1 say (K_0', D_0') & (K_1', D_1') but T^(1)_{0}' is almost as good as T^(1)_{0} with differences in 3rd or 4th decimal place making T^(1)_{0}' as good as the factory calibration.  

Question: Why there is so much variation in intrinsic parameters as I change the number of cameras? Monocalibration, stereo calibration and multi-camera calibration all give different values of intrinsics but the extrinsic is close to the truth in all these situations. I am looking for some help in understanding this.

**Comment by ynma-hanvo** [comment]
i have also got this kind of results;    i think maybe the camera 2 is not hardware synchronized. 

but can not understand why intrinsic changes a lot even with the same calibration configurations . 

by the way, can you share how do you do Monocalibration ？
