### ISSUE TITLE
can I import rs-camera intrinsic and distortion parameters directlly?

### ISSUE THREAD

**Issue by xiesc** [ethz-asl/kalibr#352]
when I calibrate rs cam line delay parameter, the calibration pattern rapidly move at the front of the camera so the distortion of movement can be obvious. But, may be, I think it is undesired for intrinsic parameters calibration, which require the pattern should be "still". Consequently, another set of images is used to calibrate the intrinsic parameters, but I can't find the entrance to directly import the intrinsic parameters when I calibrate the time delay. Is this possible to directly import cam parameters like --cam arg in "camera-imu-calibration"? Thanks a lot.

**Comment by goldbattle** [comment]
Not at this time, see https://github.com/ethz-asl/kalibr/issues/23
