### ISSUE TITLE
Possibility of removing catkin_simple

### ISSUE THREAD

**Issue by YoshuaNava** [ethz-asl/kalibr#355]
Dear Kalibr developers,

Thank you very much for this very cool package.

I'm a user of Kalibr in an industrial setting, and I really appreciate its features, stability and documentation. However, we try to manage carefully our package dependencies and that's something catkin_simple and the current structure of Kalibr doesn't fulfill, due to the use of catkin_simple and other non-ROS catkinized packages (e.g. eigen_catkin)

By means of this issue I would like to suggest removing catkin_simple and the aforementioned packages, and use cmake+catkin. If the developers are OK with this, I could submit a pull request with the required changes.

Best regards,
Yoshua Nava

**Comment by goldbattle** [comment]
I don't think at this time since most people will use this package in a one-off case.
