### ISSUE TITLE
Issue with binaries

### ISSUE THREAD

**Issue by kvmanohar22** [ethz-asl/kalibr#356]
I am doing imu-camera calibration and the results obtained from binaries and building from source are way off. In fact, the final optimization step does not converge at all by using binaries linked above. Since the binaries seem to be updated around 2014, it seems good time to update them or remove them completely? 

Also, while on this topic, many of the issues raised here concern imu-camera calibration might arise from using the binaries.

**Comment by goldbattle** [comment]
Use the docker / master.
