### ISSUE TITLE
no matching function for call to 'getOptimalNewCameraMatrix......'

### ISSUE THREAD

**Issue by RoseWillow** [ethz-asl/kalibr#359]
I am trying to build the kalibr,but it return some errors as:
/home/gyh/kalibr_workspace/src/kalibr/aslam_cv/aslam_imgproc/src/UndistorterBase.cpp:146:102:   required from here
/home/gyh/kalibr_workspace/src/kalibr/aslam_cv/aslam_imgproc/include/aslam/implementation/PinholeUndistorter.hpp:108:86: error: no matching function for call to ‘getOptimalNewCameraMatrix<aslam::PinholeUndistorter<aslam::cameras::RadialTangentialDistortion, aslam::cameras::ImageMask>::distorted_geometry_t>(boost::shared_ptr<aslam::cameras::CameraGeometry<aslam::cameras::PinholeProjection<aslam::cameras::RadialTangentialDistortion>, aslam::cameras::GlobalShutter, aslam::cameras::ImageMask> >&, cv::Size, double&, cv::Size)’
   idealCameraMatrix = aslamcv_helper::getOptimalNewCameraMatrix<distorted_geometry_t>(
                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
                                                         _distortedGeometry, cv::Size(width, height),
                                                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                                         alpha, cv::Size(newWidth, newHeight));
                                                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by lyhan12** [comment]
this compile issue can be fixed by changing "CvSize" into "cv::Size" in file kalibr/aslam_cv/aslam_imgproc/include/aslam/implementation/aslamcv_helper.hpp
