### ISSUE TITLE
Cameras are not connected through mutual observations

### ISSUE THREAD

**Issue by liubamboo** [ethz-asl/kalibr#364]
when I ran command below to calibrate realsense D435i rgb cemera, the bug always appears

command: kalibr_calibrate_cameras --target ~/project/calibration/rgb/april_6x6_A4.yaml --bag ~/disk/datasets/realsense-dataset/calibration/rgb/rgb.bag --models pinhole-radtan --topics /camera/color/image_raw --bag-from-to 20 80 --show-extraction
 
Cameras are not connected through mutual observations, please check the dataset. Maybe adjust the approx. sync. tolerance.
Traceback (most recent call last):
  File "/home/n609/software/kalibr_workspace/devel/bin/kalibr_calibrate_cameras", line 15, in <module>
    exec(compile(fh.read(), python_script, 'exec'), context)
  File "/home/n609/software/kalibr_workspace/src/kalibr/aslam_offline_calibration/kalibr/python/kalibr_calibrate_cameras", line 447, in <module>
    main()
  File "/home/n609/software/kalibr_workspace/src/kalibr/aslam_offline_calibration/kalibr/python/kalibr_calibrate_cameras", line 204, in main
    graph.plotGraph()
  File "/home/n609/software/kalibr_workspace/src/kalibr/aslam_offline_calibration/kalibr/python/kalibr_camera_calibration/MulticamGraph.py", line 311, in plotGraph
    edge_label=self.G.es["weight"],
KeyError: 'Attribute does not exist'

I try to add --approx-sync like this:
kalibr_calibrate_cameras --target ~/project/calibration/rgb/april_6x6_A4.yaml --bag ~/disk/datasets/realsense-dataset/calibration/rgb/rgb.bag --models pinhole-radtan --topics /camera/color/image_raw --bag-from-to 20 80 --show-extraction --approx-sync 0.01

but it doesn't work.and I try to change the Hz of rgb cemera.but it doesn't work too. now I don't know how I can solve it. Anyone body know how to fix the problem? if you know , please tell me ,thanks very much!

**Comment by armanhamzehlou** [comment]
I just had this issue couple of hours ago and I tried increasing approx-sync to 5. it no longer complained.

**Comment by GGDali** [comment]
modify the file  aslam_offline_calibration/kalibr/python/kalibr_camera_calibration/MulticamGraph.py at line 83
#############################################################    
    #check if all cams are connected through observations
    def isGraphConnected(self):
        #check if all vertices are connected
        return self.G.adhesion()

        if self.numCams == 1:
            # Since igaph 0.8, adhesion correctly returns 0 for the non-connected one cam case.
            #   which evaluates to false later on. So we skip the check and return true in the one camera case.
            return True
        else:
            #check if all vertices are connected
            return self.G.adhesion()

    #returns the list of cam_ids that share common view with the specified cam_id
    def getCamOverlaps(self, cam_id):

**Comment by GGDali** [comment]
modify the file  aslam_offline_calibration/kalibr/python/kalibr_camera_calibration/MulticamGraph.py at line 83 
`#############################################################    
    #check if all cams are connected through observations
    def isGraphConnected(self):
        #check if all vertices are connected
        return self.G.adhesion()

        if self.numCams == 1:
            # Since igaph 0.8, adhesion correctly returns 0 for the non-connected one cam case.
            #   which evaluates to false later on. So we skip the check and return true in the one camera case.
            return True
        else:
            #check if all vertices are connected
            return self.G.adhesion()

    #returns the list of cam_ids that share common view with the specified cam_id
    def getCamOverlaps(self, cam_id):`

**Comment by bednarhonza** [comment]
Thanks! Actually, this should be changed in the code for everybody. Could you please do it? You have saved me a lot of time..

**Comment by liaozihang** [comment]
> modify the file aslam_offline_calibration/kalibr/python/kalibr_camera_calibration/MulticamGraph.py at line 83
> `#############################################################
> #check if all cams are connected through observations
> def isGraphConnected(self):
> #check if all vertices are connected
> return self.G.adhesion()
> 
> ```
>     if self.numCams == 1:
>         # Since igaph 0.8, adhesion correctly returns 0 for the non-connected one cam case.
>         #   which evaluates to false later on. So we skip the check and return true in the one camera case.
>         return True
>     else:
>         #check if all vertices are connected
>         return self.G.adhesion()
> 
> #returns the list of cam_ids that share common view with the specified cam_id
> def getCamOverlaps(self, cam_id):`
> ```

thx

**Comment by mzahana** [comment]
@stereolabs Can you please adapt these changes in your Docker image?

**Comment by alwynmathew** [comment]
@mzahana thank you for [your docker image](https://hub.docker.com/r/mzahana/kalibr) for the single image kalibr tool.

**Comment by mzahana** [comment]
@alwynmathew you are welcome !

**Comment by Pplll-pppl** [comment]
@mzahana 

Hi, have you adapted these changes you mentioned in your Kalibr docker image?
