### ISSUE TITLE
Is IMU required for stereo calibration?

### ISSUE THREAD

**Issue by jaypatravali** [ethz-asl/kalibr#366]
Hi.
I recently got two FLIR blackfly cameras for setuping a stereo rig. 
I have setup Kalibr and tried out their static bag file. Now I am doing the same with my camera streams, Is the IMU readings required for calibration?

**Comment by floriantschopp** [comment]
No, for the camera intrinsics and camera-camera extrinsics calibration (e.g. `kalibr_calibrate_cameras`), IMU readings are not required given that the field of views of the cameras have enough overlap. If not, the extrinsics are not  observable which then might be solved by calibrating both cameras wrt the IMU.
