### ISSUE TITLE
bug: Mark all duplicate tags

### ISSUE THREAD

**Issue by KayTsao** [ethz-asl/kalibr#376]
Hi, 

I think the variable in the 2nd and 3rd statement should also be j. 

https://github.com/ethz-asl/kalibr/blob/cb6fb66dcf45d1684f8ccee4f4018930f6407ab0/aslam_cv/aslam_cameras_april/src/GridCalibrationTargetAprilgrid.cpp#L173

BR

**Comment by Andycheng0614** [comment]
yes, I also think it is a bug!
