### ISSUE TITLE
How to calibrate a circular camera system

### ISSUE THREAD

**Issue by sklf** [ethz-asl/kalibr#378]
Thanks for your project!  I built a circular 12-camera system and tried to use Kalibr  to calibrate it. But I found Kalibr only output translation matrix **T_cn_cnm1** between camera_n and camera_n-1. So in my case, I will multiply these matrices 11 times to get the transformation matrix of the  camera _11  relative to the master camera_0. I want to know if there are other ways to avoid multiplying so many times. Because I am worried that so many products will bring cumulative error. Thanks!

![image](https://user-images.githubusercontent.com/22724048/89733098-bdeaab00-da85-11ea-84b2-6de7beb1e3d5.png)

**Comment by goldbattle** [comment]
It is equivalent and you should have no issues.
Make sure you use the closed-form SE(3) inverse:
https://math.stackexchange.com/questions/1234948/inverse-of-a-rigid-transformation
