### ISSUE TITLE
How to fix intrinsics of each camera when calibrate the extrinsics of multi-camera system?

### ISSUE THREAD

**Issue by xtsxisaxns** [ethz-asl/kalibr#382]
I have already calibrated the intrinsics of each camera, I want to capture some images in the overlapping region and calibrate the extrinsics of the system. How I can do that?

**Comment by ynma-hanvo** [comment]
same question here,   i found my mulitply cameras（2 group of 2 stereo )  calibration  the camera giving not desiring K and D for each pair of camera.

**Comment by goldbattle** [comment]
Track this via issue https://github.com/ethz-asl/kalibr/issues/23
