### ISSUE TITLE
ceres lib installation failed 

### ISSUE THREAD

**Issue by vishals1010** [ethz-asl/kalibr#389]
ceres lib installation failed for camera calibration parameter for the kaliber package for camera-imu calibration 

we follow the https://blog.csdn.net/jz1570551401/article/details/78207208

for command the make .. we get this error 

-- Detected Ceres version: 2.0.0 from /home/vishal/ceres-solver-master/include/ceres/version.h
-- Detected available Ceres threading models: [CXX_THREADS, OPENMP, NO_THREADS]
-- Building with C++14
CMake Error at CMakeLists.txt:250 (find_package):
  Could not find a configuration file for package "Eigen3" that is compatible
  with requested version "3.3".

  The following configuration files were considered but not accepted:

    /usr/lib/cmake/eigen3/Eigen3Config.cmake, version: unknown

-- Configuring incomplete, errors occurred!
See also "/home/vishal/ceres-solver-master/build/CMakeFiles/CMakeOutput.log".

**Comment by goldbattle** [comment]
Please try the master now and reopen if still an issue, thanks!
