### ISSUE TITLE
radTan model compatible with image_proc ?

### ISSUE THREAD

**Issue by devbharat** [ethz-asl/kalibr#39]
The radial-tangantial model in image_proc requires 5 vector, and kalibr provides a 4 vector.  The equidist model is not implement in image_proc as well. Is there a quick way to use calibration data obtained through kalibr with image-proc ?

**Comment by rehderj** [comment]
Please note that in many cases the 5th parameter of the radial-tangetial is not estimated and instead assumed to be zero. (Please see the different occurrences of **kc(5)** on [this page](http://www.vision.caltech.edu/bouguetj/calib_doc/htmls/parameters.html))

Cheers!

**Comment by rehderj** [comment]
Please close the issue in case this solved your problem.

**Comment by devbharat** [comment]
Yes it did, thanks!
