### ISSUE TITLE
reporojection error questions

### ISSUE THREAD

**Issue by myfmyf2222** [ethz-asl/kalibr#390]
During kalibr_calibrate_cameras calibration,the recovery errors range from -0.5 to +0.5,and the kalibr_calibrate_imu_camera calibration timeshift. In the report,the recovery errors range from -2 to +2 , which is less than 0.2,what factors can affect the rejection errors?

**Comment by goldbattle** [comment]
Motion blur can be a large one. But when you use the IMU this is another noisy sensor and can influence the results too. Hope this helps.
