### ISSUE TITLE
Multi-IMU calibration without auxiliary camera

### ISSUE THREAD

**Issue by ozgunkaratas** [ethz-asl/kalibr#411]
Hello everybody,

is it possible to omit the camera within the multi-IMU calibration? I would like to run the calibration with my two IMUs and i don't have a camera. Is it possible to run the calibration nonetheless or is a camera mandatory?

many thanks in advance!

**Comment by goldbattle** [comment]
You need to have an aiding sensor to provide pose information. Hope this helps.
