### ISSUE TITLE
Question: gravity vector in target coords

### ISSUE THREAD

**Issue by chunibyo-wly** [ethz-asl/kalibr#412]
Hello, thanks for your work!
What value should I suppose to get (`gravity vector in target coords`) when I put an april tag in this orientation
![image](https://user-images.githubusercontent.com/33208530/105625447-68079500-5e64-11eb-8a24-f743c3f7ad2d.png)

`axis Y` is up
`axis X` is right
`axis Z` is to person

I think the `gravity vector.y` is supposed to be around `-9.8`, am I right?

thanks for your reply.

_Originally posted by @chunibyo-wly in https://github.com/ethz-asl/kalibr/issues/86#issuecomment-766313491_

**Comment by lapchun** [comment]
I'm also confused about this question.

**Comment by mhyoosefian** [comment]
Hi. Yeah, the gravity vector will be `[0; -9.81; 0]` ideally if the april tag is placed vertically.

**Comment by chunibyo-wly** [comment]
thanks for you reply, and i'll close this issue
