### ISSUE TITLE
 How to optimize only Z value in landmark in optimization process 

### ISSUE THREAD

**Issue by 193769981** [ethz-asl/kalibr#427]
Thanks for your excellent work!

I'm trying to optimize landmarks in the optimization process, but it's possible that target is not a complete plane, so I need to optimize Z value separately.

I see that there is an estimatelanks parameter in CameraCalibration to specify whether to optimize landmarks, but I don't know how to only optimize Z value. Please give me some guidance.

**Comment by goldbattle** [comment]
You might want to checkout this pr: https://github.com/ethz-asl/kalibr/pull/152
Otherwise this isn't something the repo will support (only organized targets).
You would need to look into the code to see how the target is define, and implement a new optimization target cost function yourself.
