### ISSUE TITLE
 AttributeError: 'module' object has no attribute 'CalibrationOptimizationProblem'

### ISSUE THREAD

**Issue by zhengethz** [ethz-asl/kalibr#429]
When I run dynamic ，there is a error. And I don't know the reason.
problem = inc.CalibrationOptimizationProblem()
AttributeError: 'module' object has no attribute 'CalibrationOptimizationProblem'

**Comment by goldbattle** [comment]
Make sure you have built the whole system including the `incremental_calibration` package. Reopen if this is still an issue when using PR https://github.com/ethz-asl/kalibr/pull/515
