### ISSUE TITLE
a question about the optimization process

### ISSUE THREAD

**Issue by 193769981** [ethz-asl/kalibr#431]
Hello, I'd like to ask you a question about the optimization process. After initializing the graph, kalibr uses Dijkstra to get the adjacent pose, and then converts the graph to the mode of cam0 -- > cam1, cam1 -- >cam2, cam2 -- > camn. When optimizing the camn, kalibr uses the pose of the camera on the path through the camn (such as cam1, cam2... cam_n-1),and they are all optimized. What's the special significance of this incremental method? Why not switch to the mode of cam0 -- > cam1, cam0 -- > cam2, cam0 -- > camn to optimize the pose only through the observation points between cam0 and camn?

Thanks!

**Comment by goldbattle** [comment]
Both should be equivalent since they are all related to the same bspline.
