### ISSUE TITLE
What is the recommended IMU intrinsic calibration tool?

### ISSUE THREAD

**Issue by aseyfi** [ethz-asl/kalibr#433]
Hello,

Would you please let me know what is the recommended tool for IMU intrinsic calibration that can provide scales, axis misalignment, nonlinearities,...?

Thank You,
Ahmad

**Comment by mhyoosefian** [comment]
Hi,

You can use the Extended version of the Kalibr. See [here](https://github.com/ethz-asl/kalibr/wiki/Multi-IMU-and-IMU-intrinsic-calibration) for more info. Also, see [here](https://github.com/ethz-asl/kalibr/issues/189#issuecomment-978890978) for the instruction on how to use the reported matrices.

Regards,
Mohammad

**Comment by JACKLiuDay** [comment]
imu utils?

**Comment by aseyfi** [comment]
Thank you @mhyoosefian and @JACKLiuDay .
