### ISSUE TITLE
Ubuntu 18.04 python-igraph --upgrade error

### ISSUE THREAD

**Issue by seungsunkim** [ethz-asl/kalibr#435]
I am trying to install Kalibr on Ubuntu 18.04.

I ran sudo pip install python-igraph --upgrade
I get the following error.

Is there a solution?

![image](https://user-images.githubusercontent.com/83208696/118265226-cc259600-b4f3-11eb-85ef-cc2ddf54e9a1.png)

**Comment by twetto** [comment]
python-igraph drops support below python 3.6 since version 0.9.0, so you may want to download the [older 0.8.3 code](https://github.com/igraph/python-igraph/releases/tag/0.8.3) and run `python setup.py install` yourself.

**Comment by seungsunkim** [comment]
@twetto 
The python-igraph version is already installed as 0.7.1.post6-5

**Comment by aahuhu** [comment]
this problem has been solved when i ran ''pip install python-igragh''.
