### ISSUE TITLE
Invalid equation in wiki

### ISSUE THREAD

**Issue by andre-nguyen** [ethz-asl/kalibr#44]
https://github.com/ethz-asl/kalibr/wiki/IMU-Noise-Model-and-Intrinsics

Basically the symbols for the noise params

**Comment by nikolicj** [comment]
Indeed. The equations on the wiki are generated through an external website and included as svg. There was a syntax error, previously apparently ignored. Fixed.

**Comment by nikolicj** [comment]
Can you close the issue once verified?

**Comment by andre-nguyen** [comment]
Thanks!
