### ISSUE TITLE
Kalibr FOV-Distortion Model in OpenCv

### ISSUE THREAD

**Issue by Gian-Alessio** [ethz-asl/kalibr#444]
Hey Guys,

so I calibrated my camera with Kalibr using the pinhole + FOV model. So I have only one distortion coefficient. Now I would like to undistort and rectify my Image using OpenCV. What would be the equivalent camera/distortion model to use?
My guess would be: void cv::fisheye::initUndistortRectifyMap and as an input D_=(dist_coefficient, 0, 0, 0)

**Comment by NikolausDemmel** [comment]
I'm not aware that opencv has FOV implemented. Recalibrate with "pinhole-equidistant". This corresponds to opencv's fisheye model.
