### ISSUE TITLE
Extrincic calibration with Vicon system

### ISSUE THREAD

**Issue by bnespoulous** [ethz-asl/kalibr#446]
Is it possible to do extrincic camera calibration using Vicon motion capture system?
If I am not mistaken, it should be possible to use the Vicon as an IMU for my calibration, right?
If so, how should I process?

**Comment by goldbattle** [comment]
You don't need an external vicon system to perform camera calibration. If you want to perform camera-to-IMU you also don't need a vicon system, just the camera, IMU, and the calibration board.
