### ISSUE TITLE
Rectified or Unrectified image to calibrate multiple Kinect?

### ISSUE THREAD

**Issue by a-gos** [ethz-asl/kalibr#447]
Hello, I'm trying to calibrate the extrinsics of multiple cameras Kinect using the rgb sensor (the pose between the cameras).  But I don't know what topic to use:

- The recitified image (/rgb/image_rgb_color)
- The unrectified image (/rgb/image_color)

What is best? Since, when using Kalibr, I am also specifying the camera model (I think for the rgb camera is pinhole-radtan)

**Comment by goldbattle** [comment]
You can use either one. Depends on what you want to do with the final image and what downstream applications use the resulting calibration. Typically using the unrectified is better, and then using the Kalibr calibration to then perform the rectification (fixing the camera calibration value).
