### ISSUE TITLE
Missing dot in circlegrid

### ISSUE THREAD

**Issue by Hawaiii** [ethz-asl/kalibr#45]
Hi,
On line 97 of  kalibr/aslam_offline_calibration/kalibr/python/kalibr_camera_calibration/CameraCalibrator.py
a dot is missing in selfgrid.

**Comment by v0n0** [comment]
still present:
https://github.com/ethz-asl/kalibr/blob/master/aslam_offline_calibration/kalibr/python/kalibr_camera_calibration/CameraCalibrator.py#L102
