### ISSUE TITLE
Missing images & Random Walk from Allan Variance values

### ISSUE THREAD

**Issue by benjirer** [ethz-asl/kalibr#450]
Hey there!

I was reading you documentation of the "IMU Noise Model" as reference for a project. I have the following two questions:

1. There seem to two images missing in the section where the bias is discretized. Would it be possible to provide these?

2. I am confused by how the Allan Variance is used gyroscope_random_walk and accelerometer_random_walk. I have the Allan Variance for both the accelerometer and gyroscope from the Data sheet of my IMU, now I am trying to determine the covariance of the noise used to propagate the bias term through time. Is there any conversion formula to link these two values?

Thank you so much for your effort & amazing documentation!

Cheers,
Ben

**Comment by goldbattle** [comment]
There are some details added to the wiki on using a allan variance package.
The images should be working now (sometimes they don't load on first refresh).
https://github.com/ethz-asl/kalibr/wiki/IMU-Noise-Model#from-the-allan-standard-deviation-ad

Hope this helps.
