### ISSUE TITLE
Any plan for release multi-IMU rosbag file?

### ISSUE THREAD

**Issue by jongwonjlee** [ethz-asl/kalibr#452]
Hello,

I appreciate your phenomenal work. It seems like provided rosbag files are containing multi camera - single IMU data, which means that multi-IMU data is missing. I am just wondering if you are intending to release any rosbag file containing multi-IMU data so that I can test the multi-IMU calibration framework. Thanks again for your remarkable contribution!

**Comment by yangyulin** [comment]
Hi, if you want, I can share you some bags with multi-cam and multi-IMUs. 
But these IMUs and cams are not chronicled and have different frequencies.

**Comment by goldbattle** [comment]
Done.
