### ISSUE TITLE
Multi-cam calibration transformation w.r.t first cam

### ISSUE THREAD

**Issue by aswinchand** [ethz-asl/kalibr#456]
Hello,
I'm trying to implement multi-camera calibration of 4 cameras with respect to one camera (i.e, transforming cam1, cam2 & cam3 with respect to cam0, so the final q & t transformation will be T_1_0, T_2_0 & T_3_0). Can you help me what changes I have to make to achieve this?

**Comment by goldbattle** [comment]
You can just specify the your cam0 to be the first camera topic. The yaml / results file will provide this transform after you perform [multi-camera calibration](https://github.com/ethz-asl/kalibr/wiki/multiple-camera-calibration).
