### ISSUE TITLE
Which Camera topics (besides /image_raw) can be used to fill the ros bag for kalibr-calibration?

### ISSUE THREAD

**Issue by Enes1097** [ethz-asl/kalibr#457]
Hey, I'm starting to read more into Kalibr and was stumbling upon this entry in the Wiki https://github.com/ethz-asl/kalibr/wiki/bag-format#how-to-use-image-files-and-imu-data-as-csv-files

Here it's mentioned that the camera data is written in the topic /<namespace>/image_raw which is then used to create the ROS bag.

The problem I'm facing right now is that my camera "Microsoft Azure Kinect DK" is using a _rational polynomial_ distortion model, which is not supported by Kalibr, as seen here https://github.com/ethz-asl/kalibr/wiki/supported-models#distortion-models, so I can't use images from the topic /rgb/image_raw.
Because of that I thought about using the "image_proc"-Package (https://github.com/ros-perception/image_pipeline) which to my knowledge can undistort "rational polynomial" distortion models to publish an undistorted image. Sadly it only publishes it to the topics /rgb/image_color, /<namespace>/image_rect_color etc. and **not** /rgb/image_raw.

Is it possible to "fill" the rosbag with images from the topic /rgb/image_rect_color and then use it for the kalibr-calibration-procedure?

Thanks for your answers!

**Comment by goldbattle** [comment]
You can use whatever topic you want. If the images are already undistorted then you can specify no distortion with `none`. If you already have ROS topics, then you can record a bag directly without using the `kalibr_bagcreater` utility.
