### ISSUE TITLE
Most file links in documentation no longer public

### ISSUE THREAD

**Issue by JanusMirith** [ethz-asl/kalibr#472]
Due to a change in the security rules of google drive all the links in the documentation will no longer work
https://support.google.com/a/answer/10685032

The links will need to be updated

**Comment by mhyoosefian** [comment]
You may want to see [this](https://github.com/ethz-asl/kalibr/issues/467) issue.

**Comment by JanusMirith** [comment]
Oh damn, I looked through the issues I must have missed it sorry.
