### ISSUE TITLE
can not download the Calibration targets

### ISSUE THREAD

**Issue by KwanWaiPang** [ethz-asl/kalibr#478]
can not download the Calibration targets.........

**Comment by wywywy01** [comment]
you can use link data：http://robotics.ethz.ch/~asl-datasets/ijrr_euroc_mav_dataset/calibration_datasets/
and use 
rosbag info cam_april.bag 

to watch topic name，

**Comment by lvxuanxuan123** [comment]
hello, what's the camera model of the data ?

> you can use link data：http://robotics.ethz.ch/~asl-datasets/ijrr_euroc_mav_dataset/calibration_datasets/ and use rosbag info cam_april.bag
> 
> to watch topic name，

hello ,what;s the camera model of the data you provide above? thank you very much!
