### ISSUE TITLE
kalidr :Compilation  failure

### ISSUE THREAD

**Issue by zw-nuist-176** [ethz-asl/kalibr#479]
Some problems occurred during compilation.
1、sudo pip install python-igraph --upgrade

![2021-10-28 15-39-26 的屏幕截图](https://user-images.githubusercontent.com/73625146/139209489-1d574ac7-2abc-4dc4-85c3-0d49509763d9.png)

Can you solve this problem by entering such content：sudo pip3 install python-igraph --upgrade  ？

2、when"catkin build -DCMAKE_BUILD_TYPE=Release -j4"，Some problems occurred。
![2021-10-28 15-33-46 的屏幕截图](https://user-images.githubusercontent.com/73625146/139209975-e32b2cde-19f0-4a6f-ae02-9a42441e13b7.png)
![2021-10-28 15-34-15 的屏幕截图](https://user-images.githubusercontent.com/73625146/139210036-914bf40c-e0e7-45dc-8a22-98c8f802f2fa.png)

I hope you can teach me how to solve these problems? Thank you for your help.

**Comment by Ceopee** [comment]
I recommend you to use python3 instead of python 2.8. Maybe this causes the failure. Check `pip list` too see installed packages. Maybe there is related module that you need to delete. 
For the 2nd problem, it looks like a namespace issue with OpenCV.  Change [lines 350/306](https://github.com/ethz-asl/kalibr/blob/master/aslam_offline_calibration/ethz_apriltag2/src/example/apriltags_demo.cpp#L305-L306): 

```
    m_cap.set(cv::CAP_PROP_FRAME_WIDTH, m_width);
    m_cap.set(cv::CAP_PROP_FRAME_HEIGHT, m_height);
```
 and [line 383](https://github.com/ethz-asl/kalibr/blob/master/aslam_offline_calibration/ethz_apriltag2/src/example/apriltags_demo.cpp#L383):
`      cv::cvtColor(image, image_gray, cv::COLOR_BGR2GRAY);
`

**Comment by zw-nuist-176** [comment]
@Ceopee Thank you for your help, I'll give it a try. Thank you for your answer.

**Comment by zw-nuist-176** [comment]
@Ceopee Sorry to disturb you again because of my work.
I follow your suggestions and links. After the implementation, there are still errors. The green suggested namespace appears when the error is reported. After my operation (final modification, as shown in Figure 1 and Figure 2), the previous problems are solved, but new problems appear (as shown in Figure 3 and Figure 4). It makes me feel at a loss. Yes, please help me solve the problem again and successfully install kalibr. Thank you very much!
![2021-11-06 11-33-11 的屏幕截图](https://user-images.githubusercontent.com/73625146/140596846-f2fdab17-f01e-4da9-be76-807b671ea240.png)
![2021-11-06 11-33-00 的屏幕截图](https://user-images.githubusercontent.com/73625146/140596851-6daa1f2d-f889-4573-867b-650bb6fe6199.png)

![2021-11-06 11-33-39 的屏幕截图](https://user-images.githubusercontent.com/73625146/140596856-39c81992-e6c2-4038-a4f8-94e9b50ef1f2.png)
![2021-11-06 11-33-44 的屏幕截图](https://user-images.githubusercontent.com/73625146/140596859-191bd776-b748-493f-82cd-211f56339119.png)
![2021-11-06 11-34-00 的屏幕截图](https://user-images.githubusercontent.com/73625146/140596862-2eb59d9c-2343-4b2c-9562-6ad2a2604f60.png)

Wish you a happy weekend!

**Comment by Ceopee** [comment]
They have all the same namespace or Opencv C Api issues. I guess you can ignore the warnings and notes. For the errors, just go to related file like `GridCalibrationTargetCheckboard`, `GridDetector` etc. change related lines. With the same behavior make some changes like  [here ](https://github.com/ethz-asl/kalibr/blob/master/aslam_cv/aslam_cameras/src/GridDetector.cpp#L188) `CV_FONT_HERSHEY_SIMPLEX` to `cv::FONT_HERSHEY_SIMPLEX`. I am not going to look into all these error. You can basically search and find related conversions. 

_Read the error output._ It gives the clue then make some search 🎉

**Comment by Tsingkai** [comment]
Do you solve these problems? I meet these peoblems, too.
Ubuntu 20.04 LTS 
Refer to ```https://blog.csdn.net/hanyeguxingwo/article/details/121293315?spm=1001.2014.3001.5501```, I solved many problems like  changing ```CV_FONT_HERSHEY_SIMPLEX``` to ```cv::FONT_HERSHEY_SIMPLEX```,but nothing to instead CvSize……
Thx!

**Comment by zw-nuist-176** [comment]
@Tsingkai Your question ,I read someone else's post,may be the version problem.But it don't uninstall ,reinstall.  I don‘t do more work.Because I find a lot of work  to do if modify the OpenCV code to adapt constantly. There are  so many bugs ,I'm going to calibrate the  camera in different way.if you have a better solution ,please let me know.

**Comment by Tsingkai** [comment]
https://github.com/ori-drs/kalibr
Checkout this repository，I replaced all files that had errors during compilation, and then I succeeded.
It fixes all syntax problems, opencv and python3.

**Comment by zw-nuist-176** [comment]
@Tsingkai  Really good. I will practice it when I have time.

**Comment by Tsingkai** [comment]
new problem,maybe two version code caused
```  
File "kalibr_workspace/devel/bin/kalibr_calibrate_cameras", line 15, in <module>
    exec(compile(fh.read(), python_script, 'exec'), context)
  File "kalibr_workspace/src/Kalibr/aslam_offline_calibration/kalibr/python/kalibr_calibrate_cameras", line 10, in <module>
    import kalibr_camera_calibration as kcc
  File "kalibr_workspace/devel/lib/python3/dist-packages/kalibr_camera_calibration/__init__.py", line 34, in <module>
    exec(__fh.read())
  File "<string>", line 2, in <module>
  File "kalibr_workspace/devel/lib/python3/dist-packages/numpy_eigen/__init__.py", line 34, in <module>
    exec(__fh.read())
  File "<string>", line 3, in <module>
ModuleNotFoundError: No module named 'libnumpy_eigen'

```

**Comment by zw-nuist-176** [comment]
@Tsingkai so many bugs need to do. ~_~`害

**Comment by FrozenSmile** [comment]
pip uninstall igraph
sudo apt-get install python-igraph

**Comment by goldbattle** [comment]
Hi please try PR https://github.com/ethz-asl/kalibr/pull/515 to see if that solves your issue.
