### ISSUE TITLE
IR camera calibration error:No corners could be extracted

### ISSUE THREAD

**Issue by lanzipoi** [ethz-asl/kalibr#480]
I can calibrate RGB camera with kalibr,but when I calibrate IR camera,an error occurred
![image](https://user-images.githubusercontent.com/34183779/139860807-a05fbbc3-a776-4eef-9e94-7890ec805894.png)

**Comment by goldbattle** [comment]
I would check the `--show-extraction`, but generally an issue might be that the image does not have enough gradient information. You would need to do some sort of pre-processing to be able to handle this. If this is still an issue, feel free to reopen with a bag that we can debug off of, thanks!

**Comment by 1zgh** [comment]
I encountered the same problem. Here is my infrared image.
![Uploading Screenshot from 2024-04-18 11-13-20.png…]()
