### ISSUE TITLE
catkin_make Error：No route to host

### ISSUE THREAD

**Issue by JonathanLJH** [ethz-asl/kalibr#481]
![kalibr no route to host](https://user-images.githubusercontent.com/89767141/140451281-814aa093-e738-4027-9eae-e811064395bf.PNG)
My firewall is down，But I still have this problem.How can I solve the problem?
Ask for some help

**Comment by mhyoosefian** [comment]
Hi.

Go to this directory: `Home/Kalibr_workspace/src/kalibr/suitesparse`. Open `CmakeLists.txt`. Find this expression: `http://faculty.cse.tamu.edu/davis/SuiteSparse`. Replace it with this one: `https://mirror.sobukus.de/files/src/suitesparse/`. 

This error happens because some files are no longer available on the same server that was used when Kalibr was being developed.

Regards,
Mohammad

**Comment by JonathanLJH** [comment]
> Hi.
> 
> Go to this directory: `Home/Kalibr_workspace/src/kalibr/suitesparse`. Open `CmakeLists.txt`. Find this expression: `http://faculty.cse.tamu.edu/davis/SuiteSparse`. Replace it with this one: `https://mirror.sobukus.de/files/src/suitesparse/`.
> 
> This error happens because some files are no longer available on the same server that was used when Kalibr was being developed.
> 
> Regards, Mohammad

thank you

**Comment by JonathanLJH** [comment]
> Hi.
> 
> Go to this directory: `Home/Kalibr_workspace/src/kalibr/suitesparse`. Open `CmakeLists.txt`. Find this expression: `http://faculty.cse.tamu.edu/davis/SuiteSparse`. Replace it with this one: `https://mirror.sobukus.de/files/src/suitesparse/`.
> 
> This error happens because some files are no longer available on the same server that was used when Kalibr was being developed.
> 
> Regards, Mohammad

When I do what you said above, I still get the same report of error
![kalibr报错2](https://user-images.githubusercontent.com/89767141/142807817-80273ad5-af90-4fc1-b619-88a81e6bb03a.PNG)

**Comment by goldbattle** [comment]
Please try PR https://github.com/ethz-asl/kalibr/pull/515 which uses the system install of suitesparse.
