### ISSUE TITLE
Always get T=(0,0,0)

### ISSUE THREAD

**Issue by gongyue666** [ethz-asl/kalibr#484]
Hi all, nowadays I use kalibr to calibrate realsense L515 and a extend IMU. I do steps follow the tutorial , everything seems ok , but the final result get a T = (0,0,0).
![image](https://user-images.githubusercontent.com/15926228/142626379-c1fe0c8d-6634-4bac-a01b-da4de690319b.png)
my camera and imu fix like this.
![image](https://user-images.githubusercontent.com/15926228/142626591-f80952cf-a033-4c44-8d22-74dce84db54f.png)
final result like this.
have I do something wrong to get this?

**Comment by mhyoosefian** [comment]
Hi,

The time shift is too large. So are the accelerometer and gyroscope errors. This makes me think that there is a problem in the data acquisition process. My advice: plot your rosbag using `rqt` and check whether data from camera and IMU are synched. Furthermore, plot your camera and IMU coordinate frames and make sure that the rotation matrices `R_ic` and `R_ci` make sense!

Regards,
Mohammad
