### ISSUE TITLE
The focal length along x and y axis are very different. 

### ISSUE THREAD

**Issue by Lashhev** [ethz-asl/kalibr#487]
After each calibration, I get unsatisfactory results. The focal length on the x and y axis are very different. As in this example:
cam0:
  cam_overlaps: [1]
  camera_model: pinhole
  distortion_coeffs: [-0.19324774955872565, 0.0658473291152598, 0.00029907018930053344,
    -0.0001662129018857859]
  distortion_model: radtan
  intrinsics: [1307.1793378428877, 1301.0605358699895, 1038.7247645586372, 810.1779283469755]
  resolution: [2064, 1544]
  rostopic: /stereo/left/image_raw
cam1:
  T_cn_cnm1:
  - [0.9999381861482503, 0.010809945389708005, -0.002601723123986178, -0.5006753665680921]
  - [-0.010830440307702369, 0.9999093733248462, -0.007996668046747615, -0.0034653870244959477]
  - [0.0025150437935848213, 0.008024351548886002, 0.9999646415433555, 0.0006361015549255583]
  - [0.0, 0.0, 0.0, 1.0]
  cam_overlaps: [0]
  camera_model: pinhole
  distortion_coeffs: [-0.2032151070883101, 0.07218971532007894, 7.545487537168565e-05,
    0.0003283633404422551]
  distortion_model: radtan
  intrinsics: [1313.9722271268822, 1305.6143030958033, 1055.5944195556292, 808.9551370890965]
  resolution: [2064, 1544]
  rostopic: /stereo/right/image_raw

**Comment by ishipachev** [comment]
Check the scale of printed pattern. It could be that imprecise scale from cheap printers creates not a square, but rectangular pattern. Compare x size and y size with a good precision and check if there is a difference.
