### ISSUE TITLE
Unable to start imu-camera calibration

### ISSUE THREAD

**Issue by ank700** [ethz-asl/kalibr#49]
Hello, I am following the steps at https://github.com/ethz-asl/kalibr/wiki/camera-imu-calibration 
I have successfully installed kalibr from source and also sourced it in the bash file. When I try to run the dataset example using the following command 
kalibr_calibrate_imu_camera --target april_6x6.yaml --cam camchain.yaml --imu imu_adis16448.yaml --bag dynamic.bag --bag-from-to 5 45

It says   " kalibr_calibrate_imu_camera: command not found " 
Can anyone tell me what am I doing wrong?

Thanks

**Comment by Guteentak** [comment]
The same problem happened to me. Did you solve it?
