### ISSUE TITLE
How to calculate T_cn_cnm0 from T_cn_cnm1 .

### ISSUE THREAD

**Issue by EMJian** [ethz-asl/kalibr#490]
Hi. Thanks for your great contribution. I am confused about the transformation matrix (T_cn_cnm1). In the Yaml formats, camera extrinsic transformation, always with respect to the last camera in the chain (e.g. cam1: T_cn_cnm1 = T_c1_c0, takes cam0 to cam1 coordinates. Now I want to calculate transformation matrix T_cn_cnm0  from matrix T_cn_cnm1, where the transformation T_cn_cnm0  should be with respect to the first camera (e.g. cam0: T_cn_cnm0 = T_c0_c1, takes cam1 to cam0 coordinates). I try to calculate transformation matrix T_cn_cnm0 with the inverse matrix of T_cn_cnm1. Please correct me if I am wrong. However, the results are faulty. 
Could you tell me how to do it if you know it? Thanks a lot.

**Comment by mhyoosefian** [comment]
Hi,

This short note of mine may help you.

[Transformation.pdf](https://github.com/ethz-asl/kalibr/files/7777042/Transformation.pdf)
