### ISSUE TITLE
Downloads are not open source

### ISSUE THREAD

**Issue by maghauke** [ethz-asl/kalibr#495]
Hi, is it possible to make all the different datasets under [downloads](https://github.com/ethz-asl/kalibr/wiki/downloads) open source?

**Comment by mhyoosefian** [comment]
Hi,

See [this](https://github.com/ethz-asl/kalibr/issues/467) issue.

Regards,
Mohammad

**Comment by goldbattle** [comment]
See this issue https://github.com/ethz-asl/kalibr/issues/514
