### ISSUE TITLE
waiting for the calibration result of camera-imu so so long!

### ISSUE THREAD

**Issue by JACKLiuDay** [ethz-asl/kalibr#496]
I tried imu bag and stereo bag and launch the camera and imu calibration, but it takes so long time .After tow hours ,I am still waiting for the result...... Is there something wrong?

**Comment by GarethZhang** [comment]
What's your build command?

**Comment by JACKLiuDay** [comment]
> What's your build command?

Just catkin_make.Is my build command not right?

**Comment by JACKLiuDay** [comment]
I try to build the package with release command , now the calibration process is fast!!
catkin build --cmake-args -DCMAKE_BUILD_TYPE=Release
like this ... and it works!
