### ISSUE TITLE
CDE package not longer public

### ISSUE THREAD

**Issue by alwynmathew** [ethz-asl/kalibr#506]
The [GDrive link](https://drive.google.com/file/d/0B0T1sizOvRsUVDBVclJCQVJzTFk/edit?usp=sharing) to kalibr CDE package is no longer downloadable. The link now redirects to a "Request Access" gdrive page.

**Comment by JessicaBertolasi** [comment]
Hi, I have the same problem, how did you fixed it? I cant't download anything!

**Comment by redchillipadi** [comment]
I am trying to use the docker image as described in https://github.com/ethz-asl/kalibr/wiki/installation as a work around for now.

**Comment by JessicaBertolasi** [comment]
ok thaks! but how do you fix the CDE packages problem? because without them i can't do anything ....

**Comment by carlosfloar** [comment]
Hi, I have the same problem to download the CDE, the link redirects to google drive where they report that "Sorry, the file you requested does not exist.", Does anyone know of another source?

**Comment by alwynmathew** [comment]
You can use this docker image https://hub.docker.com/r/stereolabs/kalibr

**Comment by goldbattle** [comment]
See this issue https://github.com/ethz-asl/kalibr/issues/514
