### ISSUE TITLE
An error occurred while compiling on ubuntu20.04

### ISSUE THREAD

**Issue by OldCatCookie** [ethz-asl/kalibr#508]
**When I tried to compile on Ubuntu20.04, the terminal returned the following error and failed to compile. What should I do about it？**

![屏幕截图 2022-03-25 185430](https://user-images.githubusercontent.com/80321238/160108904-fc6d6a49-9ef8-46e3-8c39-e8668a416171.png)

**Comment by chutsu** [comment]
I believe Kalibr hasn't updated their code base to use OpenCV 4.0+ yet, there are other forks of Kalibr such as https://github.com/ori-drs/kalibr that seems to support opencv 4. Hope this helps

**Comment by goldbattle** [comment]
Please tryout PR https://github.com/ethz-asl/kalibr/pull/515 to see if this solves your issue.
