### ISSUE TITLE
could not download aprilgrid

### ISSUE THREAD

**Issue by ROSNovice** [ethz-asl/kalibr#509]
hi i could not download the aprilgrid for calibration, do you have the other link?

**Comment by Zhefan-Xu** [comment]
You can generate one by yourself. There is no difference.

**Comment by shahaizi0** [comment]
kalibr_create_target_pdf --type apriltag --nx 6 --ny 6 --tsize 0.08 --tspace 0.3

**Comment by goldbattle** [comment]
See this issue https://github.com/ethz-asl/kalibr/issues/514
