### ISSUE TITLE
Google Drive Download Wiki Links Broken

### ISSUE THREAD

**Issue by goldbattle** [ethz-asl/kalibr#514]
The google drive links on the download page don't work for me.
https://github.com/ethz-asl/kalibr/wiki/downloads
Here are files that I have download for others to use.

### CDE-packages
- Use the docker image from [Stereo Labs](https://www.stereolabs.com/)
- https://github.com/ethz-asl/kalibr/wiki/installation#c-using-through-docker
- https://hub.docker.com/r/stereolabs/kalibr

### Sample datasets
- Use the EurocMav calibration datasets instead 
- http://robotics.ethz.ch/~asl-datasets/ijrr_euroc_mav_dataset/calibration_datasets/ 
- Camera calibration: http://robotics.ethz.ch/~asl-datasets/ijrr_euroc_mav_dataset/calibration_datasets/cam_april/cam_april.bag
- Calibration board: http://robotics.ethz.ch/~asl-datasets/ijrr_euroc_mav_dataset/calibration_datasets/cam_april/april_6x6.yaml
- Camera-IMU calibration: http://robotics.ethz.ch/~asl-datasets/ijrr_euroc_mav_dataset/calibration_datasets/imu_april/imu_april.bag

### Calibration targets

- Aprilgrid 6x6 0.8x0.8 m (A0 page) - [target pdf april_6x6_80x80cm_A0.pdf](https://github.com/ethz-asl/kalibr/files/8514447/april_6x6_80x80cm_A0.pdf) and [config yaml april_6x6_80x80cm.yaml](https://github.com/ethz-asl/kalibr/files/8514415/april_6x6_80x80cm.yaml.txt)
- Generate it yourself with `kalibr_create_target_pdf --type apriltag --nx 6 --ny 6 --tsize 0.08 --tspace 0.3`
- If you have the other please post below...

### IMU configurations

- ADIS 16448 - [config yaml imu_adis16448.yaml](https://github.com/ethz-asl/kalibr/files/8514413/imu_adis16448.yaml.txt)

---

It seems to be a common issue:
- #510
- #512
- #506
- #495
- #467
- #474
- #476
- #472
- #478
- #509

**Comment by goldbattle** [comment]
Wiki has been updated.

**Comment by sadsasuke** [comment]
@goldbattle  there are where can I find bag file examples in datasets?

**Comment by goldbattle** [comment]
First column on the download wiki page.
