### ISSUE TITLE
bagextractor 

### ISSUE THREAD

**Issue by wwendy233** [ethz-asl/kalibr#519]
When extracting pictures from bag, how can I extract the timestamps of the pictures and generate .txt / .csv files?

**Comment by wwendy233** [comment]
How to save the image timestamp to txt/csv in addition to the file name?

**Comment by wwendy233** [comment]
Now, the images' timestamps can be seen in the image's filename, and the imu's timestamps can be saved to txt/csv. But I want to save the images' timestamps additionally to txt/csv. What should I do?

**Comment by goldbattle** [comment]
I don't think this is something that is supported. You would need to edit the script to do this, or write a second script yourself.
