### ISSUE TITLE
IMU-Camera Calibration RuntimeError: Optimization failed!

### ISSUE THREAD

**Issue by xyflzyn** [ethz-asl/kalibr#533]
![image](https://user-images.githubusercontent.com/96157991/173516249-d27bbeb9-2947-40e2-ac92-b4ea4187d3ae.png)
I have tried increasing the timeOffsetPadding, but it does not work. Is there any other solution？ Thank you very much！

**Comment by goldbattle** [comment]
Likely your timestamps are inaccurate or in different clock frames. I
recommend inspecting these. You can also provide a bag for others to use to
debug.

**Comment by xyflzyn** [comment]
@goldbattle  Hello, thank you for your reply. This is the relevant file for my calibration. Could you please check if there is any problem? Thank you very much

**Comment by xyflzyn** [comment]
@goldbattle Hello, thank you very much for your answer. I have done time stamp synchronization before and calibrated a result, but this result seems not quite right.
[report-imucam-camera_imu0606_20.pdf](https://github.com/ethz-asl/kalibr/files/8905060/report-imucam-camera_imu0606_20.pdf)
And then I increased the speed of movement at the time of calibration and I had this problem.

**Comment by goldbattle** [comment]
Looking at it, it seems that the IMU isn't giving any data? Seems to all be zero? Is your imu topic scaled properly with gravity inside of it?

**Comment by xyflzyn** [comment]
@goldbattle This is the imU data we recorded. Could you please check if there is any problem？
[imu0.csv](https://github.com/ethz-asl/kalibr/files/8905257/imu0.csv)

**Comment by Weakwater13** [comment]
@xyflzyn Hello,I have the same problem. Have you solved it?

**Comment by xyflzyn** [comment]
@Weakwater13 Unfortunately, this problem has not been solved at present

**Comment by goldbattle** [comment]
Can you provide the whole bag that has the issue? The report you sent looks reasonable along with the IMU csv. Additionally, I would check that you are still able to extract when you have more dynamic motion in each frame with the `--show-extractions` flag. Hope this helps you debug your system.

**Comment by xyflzyn** [comment]
@goldbattle Thank you very much for your help,  the whole bag is too large to upload to Github. Could you please give me your email adress? I'll send it to you through it.

**Comment by xyflzyn** [comment]
[image0620.zip.001.zip](https://github.com/ethz-asl/kalibr/files/8998685/image0620.zip.001.zip)

**Comment by xyflzyn** [comment]
[image0620.zip.002.zip](https://github.com/ethz-asl/kalibr/files/8998709/image0620.zip.002.zip)

**Comment by xyflzyn** [comment]
[image0620.zip.003.zip](https://github.com/ethz-asl/kalibr/files/8998745/image0620.zip.003.zip)

**Comment by xyflzyn** [comment]
[image0620.zip.004.zip](https://github.com/ethz-asl/kalibr/files/8998756/image0620.zip.004.zip)

**Comment by xyflzyn** [comment]
[image0620.zip.005.zip](https://github.com/ethz-asl/kalibr/files/8998759/image0620.zip.005.zip)

**Comment by goldbattle** [comment]
Hi, I was unable to extract your image zip files, feel free to upload the rosbag to a better place. Looking at your YAMLs, your IMU is only 50hz? This might also be source of error (personally I have not used an IMU that low...). Additionally please provide the commands you are running and the result pdf for the static calibration. What reprojection error are you seeing?

**Comment by xyflzyn** [comment]
> 嗨，我无法提取您的图像 zip 文件，请随时将 rosbag 上传到更好的地方。看看你的 YAML，你的 IMU 只有 50hz？这也可能是错误的来源（我个人没有使用过那么低的 IMU……）。此外，请提供您正在运行的命令和静态校准的结果 pdf。你看到什么重投影错误？

**Comment by xyflzyn** [comment]
> 嗨，我无法提取您的图像 zip 文件，请随时将 rosbag 上传到更好的地方。看看你的 YAML，你的 IMU 只有 50hz？这也可能是错误的来源（我个人没有使用过那么低的 IMU……）。此外，请提供您正在运行的命令和静态校准的结果 pdf。你看到什么重投影错误？

**Comment by xyflzyn** [comment]
> Hi, I was unable to extract your image zip files, feel free to upload the rosbag to a better place. Looking at your YAMLs, your IMU is only 50hz? This might also be source of error (personally I have not used an IMU that low...). Additionally please provide the commands you are running and the result pdf for the static calibration. What reprojection error are you seeing?

Thank you for your help. The frequency of IMU we u
[report-imucam-image0620.pdf](https://github.com/ethz-asl/kalibr/files/9386010/report-imucam-image0620.pdf)
se is indeed 50Hz. This is the PDF file we calibrated @goldbattle
[report-imucam-image0620.pdf](https://github.com/ethz-asl/kalibr/files/9386011/report-imucam-image0620.pdf)

**Comment by goldbattle** [comment]
Feel free to reopen with the bag and commands if you have them.
This seems to be an IMU problem from your example result file (ensure you are using the latest master when you try again).
