### ISSUE TITLE
The result of calibration matrix is very bad！！！

### ISSUE THREAD

**Issue by xyflzyn** [ethz-asl/kalibr#539]
![image](https://user-images.githubusercontent.com/96157991/176624343-f7e6e1d7-6a8d-422a-a452-489d179b84bd.png)

**Comment by xyflzyn** [comment]
[report-imucam-image0620.pdf](https://github.com/ethz-asl/kalibr/files/9017658/report-imucam-image0620.pdf)

**Comment by xyflzyn** [comment]
# 533

**Comment by xyflzyn** [comment]
#533

**Comment by xyflzyn** [comment]
I have calibrated a matrix, but the effect is not good in use, I do not know the reason, please help to analyze, thank you very much

**Comment by goldbattle** [comment]
Closing so we just keep track of everything in #533
