### ISSUE TITLE
__VA_ARGS__ is not expanded as an argument && errors come from the Boost Python

### ISSUE THREAD

**Issue by GooseGoo** [ethz-asl/kalibr#547]
Hello, I am trying to port your code to Windows for use. However, I encountered some problems. The first problem is macro substitution.  In Visual Studio, the __VA_ARGS__ is not expanded as an argument, but as a whole argument. The second problem is errors from the Boost Python library. The errors are "boost: : python: : converter: : arg_rvalue_from_python < T > : no suitable default constructor is available ", and "base: it is initialized " in sm_python. Can you help me to slove these problems? The sincerity anticipates your reply. Thanks

**Comment by goldbattle** [comment]
Hi, this project only support Ubuntu operating systems.
