### ISSUE TITLE
IMU-Camera extrinsic calibration:camera 8-parameter rational polynomial distortion model support

### ISSUE THREAD

**Issue by LPXingxing** [ethz-asl/kalibr#548]
i'm using kalibr_calibrate_imu_camera to calibrate my stereo camera and imu system. But the "Plumb Bob" distortion_coeffs only support 5 parameters. But our camera's distortion parameter used 8 parameters(k1 k2 p1 p2 k3 k4 k5 k6).

Can you help check if kalibr_calibrate_imu_camera can support 8-parameter rational polynomial distortion?

**Comment by goldbattle** [comment]
Cameras are implemented in here:
- https://github.com/ethz-asl/kalibr/tree/master/aslam_cv/aslam_cameras
- https://github.com/ethz-asl/kalibr/blob/master/aslam_cv/aslam_cameras/include/aslam/cameras/RadialTangentialDistortion.hpp
- https://github.com/ethz-asl/kalibr/blob/master/aslam_cv/aslam_cameras/include/aslam/cameras/implementation/RadialTangentialDistortion.hpp#L5-L25

Kalibr does not use the higher order parameters `k3 k4 k5 k6` as you mention, so you would need to implement that yourself if you wanted it.
https://github.com/ethz-asl/kalibr/wiki/supported-models#camera-models

---

Here is the documentation we use in [OpenVINS](https://docs.openvins.com/update-feat.html#distortion-radtan):
![image](https://user-images.githubusercontent.com/2222562/181007496-73b6eb6b-52c7-4ffd-9fd6-de7855dd0b0c.png)


Hope this helps.

**Comment by ZeyaddMahmoudd** [comment]
@LPXingxing Have you implemented 8 coefficients distortion model?
