### ISSUE TITLE
Optimization failed!

### ISSUE THREAD

**Issue by Narcissuscyn** [ethz-asl/kalibr#55]
Can anyone tell me how to solve this problem:

Exception in thread block: [aslam::Exception] /var/kalibr-build/src/kalibr/aslam_nonparametric_estimation/aslam_splines/src/BSplineExpressions.cpp:447: toTransformationMatrixImplementation() assert(_bufferTmin <= _time.toScalar() < _bufferTmax) failed [763.696 <= 763.746 < 763.746]: Spline Coefficient Buffer Exceeded. Set larger buffer margins!

**Comment by rehderj** [comment]
Hi,
thank you for using our software. Please see other issues (also closed ones and in particular https://github.com/ethz-asl/kalibr/issues/41) for explanations on that issue.
Also, in the "extended-kalibr" branch,  there is an option of adapting the parameter: https://github.com/ethz-asl/kalibr/wiki/Multi-IMU-and-IMU-intrinsic-calibration#3-running-the-calibration .
**However, that you are experiencing this problem likely hints to an underlying issue with your dataset.**
Cheers!

**Comment by Narcissuscyn** [comment]
Hi,
     Thanks a lot!
     I have tried many datasets,sometimes it  failed,or got unreasonable results.I am not sure whither the imu.yaml is correct.I get noise desity  from the datasheet and the randwalk from allan deviation plot.I increased the timeOffsetPadding,it woks with the full dataset,but  it failed with fewer data with --bag-from-to .

**Comment by rehderj** [comment]
The values set in imu.yaml will have an impact on the precision, but in our experience, they can set within a broad range without leading to failures in the calibration. Hence, it is more likely that there are issues with your dataset.
As always, I would suspect **timing** as the culprit. We have posted extensively on this in the issues and also addressed it in a recent work (http://ieeexplore.ieee.org/xpl/articleDetails.jsp?arnumber=7445934) so please see these for starting point.

**Comment by Narcissuscyn** [comment]
Issuses with my dataset? can you  give me some examples? I have strictly organized the input datasets as  Requirements and  can't find any problem. Always thanks for your advice，i will refer to this material.

**Comment by Narcissuscyn** [comment]
thanks for your advice! I managed to solve the problem by  adjust the value of noise density and bias random walk. The result is good now.

**Comment by Yvala** [comment]
Thanks for this conversation. It was a great help for me as well. However, just from curiosity, what can be the issues with my dataset? Some examples would be helpful, since I think I have my noise density and bias random walk set properly.

**Comment by rehderj** [comment]
Please see for example issue https://github.com/ethz-asl/kalibr/issues/46 for suggestions. In our experience, noise parameters and the specific motion play a less important role (within bounds of course). Commonly, inadequate system design is the main cause for bad results.

Here an incomplete list of possible problems:
-  incorrect timestamping fo the measurements
- use of rolling shutter cameras (not supported right now)
- poorly calibrated camera intrinsics
- spurious measurement from the IMU
- motion blur

Please check your data for any of these issues.

Cheers!
