### ISSUE TITLE
The cameras are not connected through mutual target observations! Please provide another dataset...

### ISSUE THREAD

**Issue by LangZiPeiDu** [ethz-asl/kalibr#554]
标定D435i的时候报错，无法生成标定数据，需要提供另一个dataset，这是我的报错信息：

*************************************************************************************

rosrun kalibr kalibr_calibrate_cameras --target checkerboard.yaml --bag mult_cam_d435i.bag --models pinhole-radtan pinhole-radtan pinhole-radtan --topics /color /infra_left /infra_right
importing libraries
Initializing cam0:
	Camera model:	  pinhole-radtan
	Dataset:          mult_cam_d435i.bag
	Topic:            /color
	Number of images: 543
Extracting calibration target corners
  Extracted corners for 543 images (of 543 images)                              
	Projection initialized to: [ 895.28080899  895.40661113  647.75742412  359.02253582]
	Distortion initialized to: [ 0.11513699 -0.23354251  0.00048682 -0.0005654 ]
Initializing cam1:
	Camera model:	  pinhole-radtan
	Dataset:          mult_cam_d435i.bag
	Topic:            /infra_left
	Number of images: 543
Extracting calibration target corners
  Extracted corners for 543 images (of 543 images)                              
	Projection initialized to: [ 417.3526174   418.87301196  427.81256676  243.43318206]
	Distortion initialized to: [-0.00517335 -0.00251272  0.0013305   0.00090247]
Initializing cam2:
	Camera model:	  pinhole-radtan
	Dataset:          mult_cam_d435i.bag
	Topic:            /infra_right
	Number of images: 543
Extracting calibration target corners
  Extracted corners for 543 images (of 543 images)                              
	Projection initialized to: [ 417.38083763  419.13104002  427.76249859  245.09232602]
	Distortion initialized to: [ 0.00173417 -0.00973484  0.00148911  0.00111103]
initializing initial guesses
[ERROR] [1659680833.373050]: The cameras are not connected through mutual target observations! Please provide another dataset...

*************************************************************************************

**Comment by goldbattle** [comment]
Please provide more information and a bag file. Likely the issue is what the error reports. "The cameras are not connected through mutual target observations!" This means the same board was not seen from both cameras at the same time. This could be either your cameras don't have a FOV overlap or their timestamps are incorrect.

Additionally, please speak english here.
