### ISSUE TITLE
IMU-Camera extrinsic calibration: Can I input undistortion images for imu-Camera extrinsic calibration 

### ISSUE THREAD

**Issue by LPXingxing** [ethz-asl/kalibr#558]
Can i undistort images using the camera intrisinc calibration parameters then sending to the Kalibr tool to do imu-Camera extrinsic calibration .  i can set the distortion_coeffs all 0 in yaml file.

**Comment by goldbattle** [comment]
You can pre-rectify the images yes, but there is no way to fix it during static camera calibration. But for IMU-to-Camera the camera intrinsics are fixed, thus what you have explained should work I believe. You can check by re-running the rectified images through the static calibration to see if you get very small distortion parameters.
