### ISSUE TITLE
run kalibr_bagextractor  appear the error : ModuleNotFoundError: No module named 'numpy_eigen'

### ISSUE THREAD

**Issue by wwLin-slam** [ethz-asl/kalibr#563]
Hi,friends. when I run the `python3 kalibr_bagextractor --image-topics /cam0/image_raw /cam1/image_raw --imu-topics /imu0 --output-folder dataset-dir --bag awsome.bag`, but it appear the error:
`importing libraries
Traceback (most recent call last):
  File "kalibr_bagextractor", line 4, in <module>
    import kalibr_common as kc
  File "~/kalibr_workspace/src/kalibr/aslam_offline_calibration/kalibr/python/kalibr_common/__init__.py", line 2, in <module>
    import numpy_eigen
ModuleNotFoundError: No module named 'numpy_eigen'`

How to resolve the error? Please help me! Thanks!

**Comment by goldbattle** [comment]
Hi, is this within a docker container? or is this on your system?
Can you try building from scratch and seeing if there are any errors reported to console.
This can happen if all packages didn't build correctly, or you did not source the ROS workspace.
