### ISSUE TITLE
T_ic Matrix Question

### ISSUE THREAD

**Issue by yunkong11** [ethz-asl/kalibr#573]
Hi, now I'm a little confused about T_ic, how can it be decomposed into rotation matrix and translation matrix, I need your answer urgently, thank you！

**Comment by goldbattle** [comment]
This is an SE(3) transform.
![image](https://user-images.githubusercontent.com/2222562/197199461-843df7c0-414c-434d-9ec9-59090ac0241a.png)

https://ingmec.ual.es/~jlblanco/papers/jlblanco2010geometry3D_techrep.pdf
https://www.seas.upenn.edu/~meam620/slides/kinematicsI.pdf
