### ISSUE TITLE
Some questions about calibration result

### ISSUE THREAD

**Issue by Lishijiang518** [ethz-asl/kalibr#576]
Hi all，
I have some questions about calibration results.

Q1：Why are the acceleration error and angular velocity error curves from the external parameters of my calibration camera a straight line?
Q2：Are there any other problems with this result？

[images_imu-report-imucam.pdf](https://github.com/ethz-asl/kalibr/files/9957226/images_imu-report-imucam.pdf)

**Comment by goldbattle** [comment]
Maybe your IMU acceleration data is bad or you have not excited the platform enough.
It looks like there is only a few orientation changes:
![image](https://user-images.githubusercontent.com/2222562/205962883-7516a4c9-c121-492a-bcd2-71f7c51d54bf.png)
