### ISSUE TITLE
IMU-Camera calibration: Export poses fails

### ISSUE THREAD

**Issue by Youras** [ethz-asl/kalibr#577]
Hello,
When I try to perform the IMU-camera calibration with the argument `--export_poses` an error is thrown at line:
`print >> f, "t x y z r11 r12 r13 r21 r22 r23 r31 r32 r33"`

I think the function exportPoses is deprecated and needs fixing.

**Comment by goldbattle** [comment]
https://github.com/ethz-asl/kalibr/blob/c52844906247b0c7fd62ef904f501468b8512a03/aslam_offline_calibration/kalibr/python/kalibr_imu_camera_calibration/IccUtil.py#L202-L214
