### ISSUE TITLE
checkerboard 8×6 NameError: global name 'errList' is not defined

### ISSUE THREAD

**Issue by heisetiantang** [ethz-asl/kalibr#579]
![微信图片_20221110220217](https://user-images.githubusercontent.com/92718554/201111878-e1602aab-2742-4df8-88c5-2bcd7cd10e23.jpg)
![微信图片_20221110220225](https://user-images.githubusercontent.com/92718554/201111892-7bb80d3d-fbad-4b46-b8dc-4b352a19de4d.jpg)
![微信图片_20221110220228](https://user-images.githubusercontent.com/92718554/201111899-12285c1f-d57f-45a0-b895-1f06d20e350c.jpg)
![微信图片_20221110220231](https://user-images.githubusercontent.com/92718554/201111902-1ad99e8d-7c7f-4513-ab57-7c1f5ac897c0.jpg)

我与作者出现了相同的问题，我的标定板是8×6的，是大于3×3的，为什么任然出现上述问题，是否可能因为april的命名方式，必须加上a*b和每一格的大小，

I have the same problem with the author. My calibration plate is 8×6, which is larger than 3×3. Why does the above problem still occur?

_Originally posted by @heisetiantang in https://github.com/ethz-asl/kalibr/issues/370#issuecomment-1310332091_

**Comment by goldbattle** [comment]
Could you provide a bag for which this fails on?

**Comment by goldbattle** [comment]
Please reopen if you have the bag.

**Comment by Spring-Lee-cpu** [comment]
I meet exactly the same question.How to solve it, please

**Comment by goldbattle** [comment]
Do you have a bag which reproduces this? If so can you upload it and share
it?

**Comment by wbl17792615320** [comment]
I encountered the same problem, the entire Internet almost no solution, I saw someone said to rewrite "errList.append" to "print", but I still misstate SyntaxError : invalid syntax

**Comment by luckydipper** [comment]
I made silly mistake, Confused sequence_time for number_of_message.
![Screenshot from 2024-07-11 10-10-38](https://github.com/ethz-asl/kalibr/assets/65158138/b7fcd2e7-c6e7-4600-b122-1d77174b89c3)
Sequence time was 53439, not 10669527

imu_info.yaml file
