### ISSUE TITLE
question about position between imu and camera 

### ISSUE THREAD

**Issue by wangjinhoon** [ethz-asl/kalibr#580]
Hi
i dont know about this so i need help
Can I not care about the position between my imu and my cameras when I actually run imu_camera_calibration?
If I care, where should I save that value?

It will be of great help to me, thank!

**Comment by goldbattle** [comment]
The calibration itself will estimate this transformation. It is crucial that this value is estimated. The script doesn't require you to input an initial guess of the camera to IMU transform and should fine it automatically.

**Comment by wangjinhoon** [comment]
Thank you for reply.
