### ISSUE TITLE
Strange calibration results

### ISSUE THREAD

**Issue by EugenKarasev** [ethz-asl/kalibr#600]
Hello!
I test **`kalibr`** to calibrate my **rolling-shutter** monocamera (**`30 fps bgr`** ) - imu (**`~49 Hz`**) system and i got these strange results.
- Should **accel errors** and **angular velocities errors** be almost zero?
- Can **IMU**  delay deviations lead to poor calibration results?

```
Calibration results
===================
Normalized Residuals
----------------------------
Reprojection error (cam0): mean 0.390402181164542, median 0.3190253610101713, std: 0.34872396538201356
Gyroscope error (imu0):
mean 8.638410884293534e-08, median 4.105800151162524e-10, std:
3.5084008002926186e-06
Accelerometer error (imu0): mean 7.797051162952767e-07, median 7.962190946218488e-11, std:
3.098689588330113e-05
Residuals
----------------------------
Reprojection error (cam0) [px]: mean 0.390402181164542, median 0.3190253610101713, std: 0.34872396538201356
Gyroscope error (imu0) [rad/s]: mean 1.2093775238010947e-10, median 5.748120211627534e-13, std:
4.9117611204096645e-09
Accelerometer error (imu0) [m/s^2]: mean 1.0915871628133875e-08, median 1.1147067324705883e-12, std:
4.3381654236621587e-07
Transformation (cam0):
-----------------------
T_ci: (imu0 to cam0):
[[-0.00000163 -0.99924041 0.03896932 -0.00002999]
[-0.23080183 -0.0379168 -0.97226171 0.00019168]
[ 0.97300078 -0.00899578 -0.23062646 -0.00002362]
[ 0. 0. 0. 1.]]
T_ic: (cam0 to imu0):
[[-0.00000163 -0.23080183 0.97300078 0.00006723]
[-0.99924041 -0.0379168 -0.00899578 -0.00002291]
[ 0.03896932 -0.97226171 -0.23062646 0.00018209]
[ 0. 0. 0. 1.]]
timeshift cam0 to imu0: [s] (t_imu = t_cam + shift)
-0.06078444965185353
Gravity vector in target coords: [m/s^2]
[-0.34105986 -9.79777889 0.23585982]Calibration configuration
=========================
cam0
-----
Camera model: pinhole
Focal length: [1039.5099570143711, 1042.2195539224472]
Principal point: [618.1704778515369, 290.37109512978014]
Distortion model: radtan
Distortion coefficients: [-0.3935934462048003, 0.16992322720688555, 0.003903623112852698,
-0.00036856266440390197]
Type: aprilgrid
Tags:
Rows: 7
Cols: 7
Size: 0.019 [m]
Spacing 0.0038 [m]
IMU configuration
=================
IMU0:
----------------------------
Model: calibrated
Update rate: 49.0
Accelerometer:
Noise density: 0.002
Noise density (discrete): 0.014
Random walk: 0.0004
Gyroscope:
Noise density: 0.0002
Noise density (discrete): 0.0014000000000000002
Random walk: 1e-05T_ib (imu0 to imu0)
[[1. 0. 0. 0.]
[0. 1. 0. 0.]
[0. 0. 1. 0.]
[0. 0. 0. 1.]]
time offset with respect to IMU0: 0.0 [s]
```

![accels](https://user-images.githubusercontent.com/50025549/226557729-7e350819-8a0a-4b57-b63f-6755fd98ad89.png)
![accels_bias](https://user-images.githubusercontent.com/50025549/226557744-ab990f5f-a84a-43f1-af24-36615a678b49.png)
![accels_err](https://user-images.githubusercontent.com/50025549/226557784-a76b75ae-b270-4279-be74-2fe238d09ea0.png)
![ang_vel](https://user-images.githubusercontent.com/50025549/226557815-b82b5dcc-f351-4738-8213-576d7f5c44fc.png)
![ang_vel_err](https://user-images.githubusercontent.com/50025549/226557849-7ed478db-77e2-4cbe-abdc-efad731c42bc.png)
![cam_proj_err](https://user-images.githubusercontent.com/50025549/226557866-d47e0afd-9f1d-480a-ba63-3c4a8329d44b.png)
![gyro_bias](https://user-images.githubusercontent.com/50025549/226557899-4b4ff7a8-36e1-4020-a76c-f1a2dc6d8400.png)
![mes_rates](https://user-images.githubusercontent.com/50025549/226557919-467e9689-aa2f-4aa7-9632-3f728406691a.png)
![trajectory](https://user-images.githubusercontent.com/50025549/226557945-3169240a-293b-4774-b688-fae12f71ebc3.png)

**Comment by goldbattle** [comment]
It looks like it didn't optimize probably. Maybe the IMU noises you are
using could be better.
