### ISSUE TITLE
about sample bag file 

### ISSUE THREAD

**Issue by hanseongbugi** [ethz-asl/kalibr#606]
I am having a hard time matching the time shift between IMU and camera frame.
So I looked up a lot of issues and found out that they provided sample bag files in the past.
If you have a chance, could you provide me with the bag file that you made in the past?
It is necessary for academic research using mobile devices.

**Comment by goldbattle** [comment]
The downloads page has example bags:
https://github.com/ethz-asl/kalibr/wiki/downloads
