### ISSUE TITLE
Did not converge to maxiteration

### ISSUE THREAD

**Issue by gitissues79** [ethz-asl/kalibr#610]
I' working on multi-camera calibration, whille calibrating the cameras, i am facing the issue "did not converge to maxiteration", I tried increasing max iterations to 500, but still it did'nt worked for me
I am using ros noetic, ubuntu 20.04

![image](https://user-images.githubusercontent.com/130313433/232590879-88eedee0-48e1-49a0-9505-92ed333c0c07.png)

**Comment by goldbattle** [comment]
Please post a bag, and take a higher resolution screenshot. Reopen when you do. Likely your camera model selected isn't proper for the camera (e.g. radtan won't work on a fisheye).
