### ISSUE TITLE
d435 extrinsic estimation with April Board

### ISSUE THREAD

**Issue by Deok-min** [ethz-asl/kalibr#611]
Hi, thank you for sharing great work.
By the way, I'm trying to estimate Transformation matrix between April board and wrist camera (rs d435).
But, the visualized result is not accurate. The projected depth image and estimated board frame is not aligned. Could you give me some advice to improve the accuracy?
![april_tag_extrinsic_rviz](https://user-images.githubusercontent.com/48019048/233985675-40506255-6a0e-4006-956d-bda8a26419c8.png)

And my code followed below steps.
1. First i measured intrinsic parameters provided code "kalibr_calibrate_rs_cameras".
2. Generate Camera.geometry using the intrinsic parameters obtained from above step.
![image](https://user-images.githubusercontent.com/48019048/233986229-629abd82-7597-49bb-be3f-9c0a704148de.png)

3. Estimate Extrinsic parameters using provided function, '_generateExtrinsicsInitialGuess()'.
![image](https://user-images.githubusercontent.com/48019048/233986574-a3c0c3fb-0bf9-4112-95fd-daea9438ec3e.png)

How can I improve the tf accuracy? Thank you for reading.

**Comment by goldbattle** [comment]
Maybe there is an additional transformation to your depth camera. Not sure.

**Comment by goldbattle** [comment]
Feel free to reopen if this is an issue with the Kalibr tools and not your implementation.
