### ISSUE TITLE
Calibration data from kalibr Event camera to RGB

### ISSUE THREAD

**Issue by shrutarv** [ethz-asl/kalibr#616]
Hello,

I have successfully calibrated a stereo setup of a DVXplorer event camera and a RGB camera using kalibr. I have a point in the event camera frame and I would like to get the corresponding point in the RGB camera frame. How to get that using the data obtained from calibration using the kalibr?

**Comment by goldbattle** [comment]
Kalibr does not support event cameras.

**Comment by JiaqiangZhang** [comment]
Hi, @shrutarv thank you for the issue.

I am working on calibrating a DVXplorer event camera stereo setup as well. Did you use the DV-GUI to calibrate, or some other tool? I followed the [official instructions](https://docs.inivation.com/software/dv/gui/calibrate-event-camera.html) to calibrate the stereo setup, but it keeps failing with high errors. 

![Image](https://github.com/user-attachments/assets/0487807f-8825-4f5f-ba9d-c8359c7d9b39)
