### ISSUE TITLE
In the Camera-IMU 's calibration report about [acceleration error] Plot, what dose the blue line means?Why can it characterize the range of accelerometer measurements and predictions?

### ISSUE THREAD

**Issue by 10179013** [ethz-asl/kalibr#618]
Why does the discrete uncertainty of accelerometer characterize the range of accelerometer measured and predicted values?

I think the blue line means：The value of the acceleration estimated using the spline minus the actual measured value of the accelerometer

I think the two red lines means：accelUncertainDiscret

In other words that is $Discrete -Uncertainty- of- Acceleration=\frac{Acceleration -noise -per- unit- frequency}{Square- root -of -the -reciprocal -of -the -acceleration update -frequency}$
![image](https://github.com/ethz-asl/kalibr/assets/52630860/00ece907-994c-46f7-98ba-6aab917742e3)

**Comment by goldbattle** [comment]
The redlines are the 3-sigma bounds which should bound the error of the estimated parameters. They basically capture what the optimizer *things* the error should be. In general if it goes out of bounds that means the data is bad or the noises used during optimization (all errors should remain bounded over time).

You can see they are flat lines as the readings are directly measurements, and thus should be covered by the white-noise at each timestep.
