### ISSUE TITLE
In the Camera-IMU 's calibration report about [estimated accelerometer bias (imu frame)] Plot, what dose the blue line means?Why can the blue line represent the credibility of the bias?

### ISSUE THREAD

**Issue by 10179013** [ethz-asl/kalibr#619]
[**estimated accelerometer bias (imu frame)**] Plot

I think the blue line means：**predict the accelerometer's bias from the B spline**

I think the two red lines means：**predict the accelerometer's bias from the B spline** ± **3 * accelerometer random walk * Prescription at each time point**

But from the plot ：

Why does the changing trend of the red line seem to be unaffected by the blue line? (Although the starting point of the two is the same. According to the meaning of the red and blue lines, the red line should have the same trend as the blue line, but the actual red line is so ideal (like an inverted normal distribution curve)) .
Excuse me:

1. Is there a mistake in my understanding of the red and blue lines?
2. Why can the blue line （**predict the accelerometer's bias from the B spline** + **3 * accelerometer random walk * Prescription at each time point**）represent the credibility of the bias?

![image](https://github.com/ethz-asl/kalibr/assets/52630860/1bfbbc72-c17e-4a6b-8c81-ef8eb958f7e7)

**Comment by goldbattle** [comment]
The redlines are the 3-sigma bounds which should bound the error of the estimated parameters. They basically capture what the optimizer *things* the error should be. In general if it goes out of bounds that means the data is bad or the noises used during optimization (all errors should remain bounded over time).
