### ISSUE TITLE
random walk from bias instability from datasheet

### ISSUE THREAD

**Issue by mnissov** [ethz-asl/kalibr#622]
In the wiki page on [IMU noise models](https://github.com/ethz-asl/kalibr/wiki/IMU-Noise-Model#from-the-datasheet-of-the-imu) it is written that:

> In combination with the strength of the "white noise", however, one can often use the in-run bias stability (the lowest point in the Allan standard deviation, see below) to determine reasonable values for and (assuming that the noise is dominated by "white noise" and a "random walk").

How one does this isn't covered by the later sections, nor by the references (as far as I know). I was curious if you had something in mind with this statement, some literature one could read on.

Given that most, in my experience,  IMU datasheets offer noise density and bias instability it would be very convenient if there was a standardized approximation procedure to get random walk out of this. If such a thing exists I am not aware of it, nor have I found a lot of literature covering it. I would really appreciate any wisdom or literature that you have on this topic.

**Comment by goldbattle** [comment]
It really depends on the datasheet. The most I have seen are the white noises being on there, but typically the bias instability isn't (could just make it 1-2 orders smaller than the white, but is very handwavy here). The correct way is to get it experimentally using an allan variance chart, which is covered on the wiki.
