### ISSUE TITLE
How to calibrate only IMU in gazebo

### ISSUE THREAD

**Issue by nicko369** [ethz-asl/kalibr#624]
How to calibrate the libgazebo IMU plugin.
Even though the plugin parameters are set to 0, there is still some noise and fluctuations even though the IMU is stationary.
Is it possible to calibrate the IMU in gazebo?
Is it possible to even calibrate at all in gazebo because the arcuo poster is needed

**Comment by goldbattle** [comment]
You should need to figure this out yourself. Gazebo is a simulation, so there will still be some small noise due to the numerical physic simulator used.
