### ISSUE TITLE
Question about the Detection failed.

### ISSUE THREAD

**Issue by hanseongbugi** [ethz-asl/kalibr#626]
I run kalib_calibrate_imu_camera with verbose option.
It printed out the phrase detection failed as a result of execution.
I made the bag file that I needed to run by myself through a mobile device.
Looking at the results output by the verbose option, it was found that the image was blurred.
I think this happened because it didn't detect the edge well even though it used a Gaussian filter.
The video collection was conducted by referring to the YouTube video.
Please let me know what kind of solution there is

**Comment by goldbattle** [comment]
You need to have good focus / sharpness to extract. Could you post a bad / picture of the problem? Additionally, you need to first perform camera calibration before IMU-camera, which will also require good quality images.

**Comment by hanseongbugi** [comment]
[https://drive.google.com/file/d/1pcRNWEPAZxH2bazmh4uzkb1RjnkuoQho/view?usp=sharing](url) here is my bag file

**Comment by goldbattle** [comment]
This looks like a case of either using a rolling shutter camera and having high motion blur. It is able to extract on still frames, but has a hard time while moving. I recommend increasing the shutter speed.
![Screenshot from 2023-06-26 08-07-35](https://github.com/ethz-asl/kalibr/assets/2222562/2c56cc0e-5c9a-455e-82ba-734b25f2b4ad)

**Comment by hanseongbugi** [comment]
Currently my camera gets frames every 5ms, imu gets data for 10ms. 
Also, my mobile device, Samsung Note 5, has a limit of 5ms of camera shutter speed.
Can you tell me if the value of 5ms is too fast or too slow to make the right result in kalibr

**Comment by goldbattle** [comment]
33ms should be fine (it is 30hz) the problem I think is the visual rolling shutter you can see. If you are able to record at a higher framerate then this could go away due to the lower exposure time.
