### ISSUE TITLE
[ERROR] [1688457338.359981]: [TargetViewTable]: Tried to add second view to a given cameraId & timestamp. Maybe try to reduce the approximate syncing tolerance..

### ISSUE THREAD

**Issue by SunilSrivatsav9** [ethz-asl/kalibr#628]
I am working on calibrating IMU-CAM setup using Kalibr. I have synchronized the IMU-CAM beforehand and collected the data by exciting all axis of IMU using ROSBAG. 

Later I tried calibrating camera but got error regarding timestamps. 
The error is given below:

**[ERROR] [1688457338.359981]: [TargetViewTable]: Tried to add second view to a given cameraId & timestamp. Maybe try to reduce the approximate syncing tolerance..**

I have also attached the rosbag info below.

```
path:        IMU-CAM-Small.bag
version:     2.0
duration:    3:41s (221s)
start:       Jul 04 2023 10:50:57.57 (1688435457.57)
end:         Jul 04 2023 10:54:38.92 (1688435678.92)
size:        1.4 GB
messages:    4428
compression: none [1108/1108 chunks]
types:       sensor_msgs/Image [060021388200f6f0f447d0fcd9c64743]
             sensor_msgs/Imu   [6a62c6daae103f4ff57a132d6f95cec2]
topics:      /camera_image   2214 msgs    : sensor_msgs/Image
             /imu            2214 msgs    : sensor_msgs/Imu
```

Can anyone suggest the solution?

**Comment by goldbattle** [comment]
Please post your rosbag. Looking at your rosbag info, it is weird that your IMU rate matches your camera. This shouldn't be the case. Also your IMU is at 10Hz? If so I believe many people have trouble with low rate IMUs and this code. You should use an IMU with rate > 100hz (400hz is much better of course).
