### ISSUE TITLE
how to set the border 1 bit for apriltag 3 detection

### ISSUE THREAD

**Issue by XavierQL** [ethz-asl/kalibr#639]
As the title described, who can share me the method? as the creat target pdf coding description, borderBits must be consitent with the variable "blackBorder" in the file ethz_apriltag2/src/TagFamily.cc, but i only see blackdorder=2 in file TagFamily.h. and I change the blackborder=1, but it doesn't work.
looking forward for help

**Comment by goldbattle** [comment]
The codebase uses AprilTag2 not 3. You can try to change the boarder amount, but all the generated boards will be with blackboarder=2 is my understanding. I remember in the past that it should work, so I recommend you inspect your implementation. I believe `aslam_cv/aslam_cameras_april/include/aslam/cameras/GridCalibrationTargetAprilgrid.hpp` has the default of 2 in it not the file you have mentioned.
