### ISSUE TITLE
Numpy_eigen.libnumpy_eigen not found

### ISSUE THREAD

**Issue by Aishkrish18** [ethz-asl/kalibr#640]
![Screenshot from 2023-08-14 12-33-46](https://github.com/ethz-asl/kalibr/assets/47241581/430982e5-3c84-4ba7-b812-a9e989669420)

![Screenshot from 2023-08-14 12-34-29](https://github.com/ethz-asl/kalibr/assets/47241581/54a40be6-e68b-47f0-a976-c2571a631f86)

Although the repository gets built, i keep gettingthis error from numpy_eigen. I really dont know how to solve this, would be better if someone could help me with this so that I can perform calibration. Was attempting to try this for calibrating for OKVIS algorithm but yeah now it entirely fails to work.

Thanks,
Aishwarya

**Comment by goldbattle** [comment]
Hi, could you please provide more information about your install? Is this in the docker container?

**Comment by goldbattle** [comment]
Please reopen with details to reproduce.
