### ISSUE TITLE
Gyro - Accelerometer units

### ISSUE THREAD

**Issue by ManChrys** [ethz-asl/kalibr#641]
Hello,

i have read a lot of issues about the units of gyroscope and accelerometer and there are different opinions about that. 

What's the correct units ? 

Thanks in advance.

**Comment by goldbattle** [comment]
Accel: m/s2
Gyro: rad/s

See the standard: https://www.ros.org/reps/rep-0145.html

**Comment by ManChrys** [comment]
Hello @goldbattle,

thanks for the response,
yeah i know that generally these are the units. But for kalibr i saw this table

![Screenshot_1](https://github.com/ethz-asl/kalibr/assets/67521662/5942362a-bae8-4073-92f5-685d65cb9709)

**Comment by goldbattle** [comment]
These are for the noise parameters. The units for them are in the last
column.

**Comment by ManChrys** [comment]
yeah i was asking about noise params which i have to fill in yaml file. Its my mistake that i didnt specified.

These units in wiki documentation are the correct right ?

**Comment by goldbattle** [comment]
Yes!
