### ISSUE TITLE
RuntimeError: FATAL: module compiled as little endian, but detected different endianness at runtime

### ISSUE THREAD

**Issue by BaotingKing** [ethz-asl/kalibr#642]
importing libraries
RuntimeError: FATAL: module compiled as little endian, but detected different endianness at runtime
Traceback (most recent call last):

  File "/usr/lib/python3/dist-packages/cv_bridge/__init__.py", line 6, in <module>
    from cv_bridge.boost.cv_bridge_boost import cvtColorForDisplay, getCvType
SystemError: initialization of cv_bridge_boost raised unreported exception

**Comment by goldbattle** [comment]
Please provide more details, thanks!
