### ISSUE TITLE
can i use other calibration models to calibrate the extrinsic parameters between imu and cameras?

### ISSUE THREAD

**Issue by zhangbb-john** [ethz-asl/kalibr#647]
I have a camera with more than 120 degree view. I used pin-hole model of kalibr with 2 parameters for radial distortion and 2 parameters for tangential distortion. However, the result is not good where the reprojection error is large, leading bad performance of extrinsic parameter calibration using kalibr. I tried pin-hole model  with 3  parameters for radial distortion and 2 parameters for tangential distortion, where the results indicate that the reprojection error is much smaller for intrinsics-calibration. So I assume can i use other calibration models to calibrate the extrinsic parameters between imu and cameras? Thanks

**Comment by goldbattle** [comment]
I believe the calibration models should be the same for both the multi-camera and camera-imu scripts.
