### ISSUE TITLE
Some errors while catkin_make -DCMAKE_BUILD_TYPE=Release -j2

### ISSUE THREAD

**Issue by Tan-B24** [ethz-asl/kalibr#650]
catkin_ws/src/kalibr/aslam_nonparametric_estimation/bsplines_python/src/BSplinePython.cpp:40:108: error: ‘_1’ was not declared in this scope
   40 |  return boost::python::make_function(boost::bind(&BiFunction<T>::getBi, BiFunction<T>(bs->getBiVector(t)), _1)
      |                                                                                                                                                                                  ^~

**Comment by goldbattle** [comment]
Please provide more details and also ensure to try the docker container.

**Comment by YechenZhou** [comment]
This link https://blog.csdn.net/nigtkk/article/details/137998334     works for me.
