### ISSUE TITLE
(Checkerboard corners:1924109): GLib-GObject-WARNING **: 17:13:34.289: cannot register existing type 'GdkDisplayManager'

### ISSUE THREAD

**Issue by ZhiYiXinNan** [ethz-asl/kalibr#659]
When I use "rosrun kalibr kalibr_calibrate_cameras --target checkerboard.yaml --bag camd435i.bag --models pinhole-equi --topics /color --show-extraction",it shows (Checkerboard corners:1924109): GLib-GObject-WARNING **: 17:13:34.289: cannot register existing type 'GdkDisplayManager'
![微信图片_20231209173900](https://github.com/ethz-asl/kalibr/assets/126838395/4f93ea32-022e-4a41-a974-3881b3ac23d6)
what can I do?

**Comment by goldbattle** [comment]
Are you running this in a docker or some container that doesn't have a display? You can try to disable showing the final pdf report and it should still save to file ok. Do you have any more details on the OS you running on and what libraries you have installed?

**Comment by 506jun** [comment]
Has the same issue been resolved?

**Comment by 506jun** [comment]
> 当我使用“rosrun kalibr kalibr_calibrate_cameras --target checkerboard.yaml --bag camd435i.bag --models pinhole-equi --topics /color --show-extraction”时，它显示（Checkerboard corners：1924109）：GLib-GObject-WARNING **: 17:13:34.289：无法注册现有类型“GdkDisplayManager” 我该怎么办？ ![微信图片_20231209173900](https://github.com/ethz-asl/kalibr/assets/126838395/4f93ea32-022e-4a41-a974-3881b3ac23d6)

How was it resolved, please?
