### ISSUE TITLE
Please add coordinate system information and clarify meaning of transformations. 

### ISSUE THREAD

**Issue by lowellm91** [ethz-asl/kalibr#662]
I have problem getting your calibration information to work with another piece of SLAM software and the issue I think is related to inconsistent coordinates. In particular in your camera-centric system the x-axis isn't forward, it's to the side which is different than the coordinate system TF2 uses http://wiki.ros.org/tf2/Terminology.

In addition I wanted to clarify what T_cam_imu  does. From what I understand it takes a vector written in the IMU coordinate system to a vector written in cam0 coordinate system, is this correct? So in order to get the location and orientation of the IMU wrt to cam0, I need to take its inverse?

**Comment by goldbattle** [comment]
You should expect the camera sensor frame to have the z-axis pointing forward, y-axis down, and x-axis to the right when viewing the from "from behind". This is the convention for computer vision / pinhole camera models.


![image](https://github.com/ethz-asl/kalibr/assets/2222562/46ca331f-19f4-49b8-b38a-8f447b75cdf9)

Do you see something different? The result pdf should visualize this for you.

**Comment by lowellm91** [comment]
Hello, I was not provided the output only the text values used by Kaliber. What about the IMU? In general it would be helpful to have this information on the website under the YAML output section.

**Comment by goldbattle** [comment]
The current wiki has what you mentioned:
> T_cam_imu
> IMU extrinsics: transformation from IMU to camera coordinates (T_c_i)

I missed your second question, yes you would take the inverse (there is a closed equation for this inverse), and this would then allow you to take a point in the camera frame and rotate + translate it into the IMU frame.

**Comment by lowellm91** [comment]
Ok thank you.

**Comment by jiheddachraoui** [comment]
hello @goldbattle ,
Are these results correct? The coordinate system seems inverted to me because I get the camera order reversed from left to right — the interpretation of the matrices only makes sense if the x-axis points left and the y-axis points upward. Could you please explain?

![Image](https://github.com/user-attachments/assets/8df5accb-517b-42e9-98c2-51bf3e5b914b)
