### ISSUE TITLE
Get Fundamental Matrix?

### ISSUE THREAD

**Issue by mcqueen003** [ethz-asl/kalibr#675]
Hi,

I have a couple of questions.
1) How can I recover an array with the detected corner points in each calibration image?
2) How can I obtain the Fundamental Matrix? I would like to use it to plot the epipolar lines in my stereo images.

My ultimate goal is to get the depth image from a given stereo pair.

Thank you

**Comment by goldbattle** [comment]
Hi, this is a calibration package. Maybe you might want to look at OpenCV on how to do these.
If you wish to use this package's extractor for the calibration target you can take look in this package:
https://github.com/ethz-asl/kalibr/tree/master/aslam_cv/aslam_cameras_april

Specifically this function might be of interest to you:
https://github.com/ethz-asl/kalibr/blob/f2e8ba46ec9101ddae020d12d0ff6bf37f426de5/aslam_cv/aslam_cameras_april/src/GridCalibrationTargetAprilgrid.cpp#L98-L101
