### ISSUE TITLE
Calibration report

### ISSUE THREAD

**Issue by Jawaheru** [ethz-asl/kalibr#683]
Hi,

am trying to run my data but I kept have warring if I run my data set says "gyroscope bias initial calibration   0.0751552   -0.103833 -0.00691748"
I cannot detect if my data is now synch. or it an imu issue,
So below is my imu cam calibrattionreport if any one can help me to analyze and enhance my yaml.
[Uploading imucam_calib7_2024-04-25-11-50-24-report-imucam.pdf…]()

Ty,

**Comment by goldbattle** [comment]
Hi, please upload a complete file and detail what exactly the problem is. feel free to reopen this with these details.
