### ISSUE TITLE
The Calibration Targets in the Wiki are all missing.

### ISSUE THREAD

**Issue by Hanning-Liu** [ethz-asl/kalibr#690]
Here is the line to the missing place:
https://github.com/ethz-asl/kalibr/wiki/downloads#calibration-targets

**Comment by Hanning-Liu** [comment]
The google drive link is invalid. Could it be fixed?

**Comment by WFram** [comment]
You can generate the pattern online or using OpenCV and fill your `.yaml` based on the given examples.

**Comment by goldbattle** [comment]
Should be updated.
