### ISSUE TITLE
My calibrated translation vector is not quite right caused by incorrect scaling of accelerometer measurements

### ISSUE THREAD

**Issue by SIRIUSwithXU** [ethz-asl/kalibr#691]
I had a problem calibrating the camera and imu. The shift vector is too large, and the imu is mounted about 5cm away from the camera. The results are as follows. Does anyone know what affected my calibration results?
![图片](https://github.com/ethz-asl/kalibr/assets/57032226/76b3dfba-7b26-426f-8cc2-737311ae1265)
![Snipaste_2024-06-11_14-06-29](https://github.com/ethz-asl/kalibr/assets/57032226/e3f77fc1-f38c-4c44-b136-86ba8c5cbf36)
![Snipaste_2024-06-11_14-06-56](https://github.com/ethz-asl/kalibr/assets/57032226/70b8b288-6ce6-45fc-9f46-93adc0f77ca1)
![Snipaste_2024-06-11_14-07-13](https://github.com/ethz-asl/kalibr/assets/57032226/0326a7ff-14f6-4191-9f7b-e4cb5a31845b)
![Snipaste_2024-06-11_14-07-58](https://github.com/ethz-asl/kalibr/assets/57032226/335d8faf-cb60-4be0-8438-f98a638e3b08)
[MY_NO011-report-imucam.pdf](https://github.com/user-attachments/files/15782967/MY_NO011-report-imucam.pdf)

**Comment by WFram** [comment]
Based on angular velocities error plot, IMU model doesn't cover the sensor noise; Same about acceleration bias. I would try to increase the values of these noises and try again. Also, the reprojection errors are large enough. Usually 0.3-0.5 px is fine -> Make sure the camera intrinsics are calibrated properly with an appropriate camera model.

**Comment by SIRIUSwithXU** [comment]
> Based on angular velocities error plot, IMU model doesn't cover the sensor noise; Same about acceleration bias. I would try to increase the values of these noises and try again. Also, the reprojection errors are large enough. Usually 0.3-0.5 px is fine -> Make sure the camera intrinsics are calibrated properly with an appropriate camera model.

Thank you for your answer. I amplified the noise level and it did get better. And then, mainly because I made a mistake, my accelerometer output is in g, which multiplied by 9.8 is m/2.
