### ISSUE TITLE
Calibration tag pdf and config url are not working

### ISSUE THREAD

**Issue by U-Abhishek** [ethz-asl/kalibr#693]
please update the URL for Aprilgrid 6x6 0.8x0.8 m (A0 page)

**Comment by bryangd34** [comment]
@U-Abhishek 
Good day, were you able to find the Aprilgrid? If so, it would be great if you could share that please.

**Comment by bryangd34** [comment]
see [509](https://github.com/ethz-asl/kalibr/issues/509)

**Comment by goldbattle** [comment]
Should be updated.
