### ISSUE TITLE
Reprojecction Error Range Clarification

### ISSUE THREAD

**Issue by geoeo** [ethz-asl/kalibr#697]
you write "reprojection errors should be in a normal range (0.1-0.2 px for a good calibration)"

Does this mean the average should be in the range 0.1-0.2 or the +/- i.e. the deviation should be within the range?

E.g. 

Is this a good result

![image](https://github.com/ethz-asl/kalibr/assets/1128542/7de0bb08-147c-4f45-8d09-4a2ab810379d)

**Comment by chenzhekl** [comment]
Hi @geoeo , I am having the same confusion as you. How did you assess your quality of calibration in the end?

**Comment by geoeo** [comment]
I think it is indeed the +/- range that should be the 0.1-0.2 range. But depending on your camera is may vary e.g. wide angle lenses
