### ISSUE TITLE
Cannot download the muti-cam ros bag file in  https://github.com/ethz-asl/kalibr/wiki/downloads

### ISSUE THREAD

**Issue by JunLFang** [ethz-asl/kalibr#700]
When I try to download the [Multi-CAM](https://drive.google.com/file/d/1rRRSoaCUQC8Jz4vCgNhmtzn3f3urqb9e/view?usp=sharing) , it show the link is invalid , could you help to update the link ? Thank you very much

**Comment by goldbattle** [comment]
Should be updated now.

**Comment by JunLFang** [comment]
@goldbattle  Thank you very much. Now I can access it
