### ISSUE TITLE
bad IMU timestamps 

### ISSUE THREAD

**Issue by Tis-Wu** [ethz-asl/kalibr#702]
As shown in the picture, the IMU timestamp for camera-IMU calibration looks abnormal. How can I rectify it?
![2024-08-02 18-39-27 的屏幕截图](https://github.com/user-attachments/assets/46046265-39ed-4686-930d-3f63c4a326cb)

**Comment by goldbattle** [comment]
This is something that would need to be addressed in the firmware / driver software of the IMU.
