### ISSUE TITLE
StereoCameras Vins Fusion

### ISSUE THREAD

**Issue by jimakos96** [ethz-asl/kalibr#703]
Hi , i have used kalibr example (https://github.com/ethz-asl/kalibr/wiki/multiple-camera-calibration ) to calibrate my stereo Cameras and i got the following result .

`                                                                                                                   
 cam0:
  cam_overlaps: [1]
  camera_model: pinhole
  distortion_coeffs: [0.005920792469494964, -0.03616664911765219, 0.037222850222450116, 0.011123305812269288]
  distortion_model: radtan
  intrinsics: [665.5152560695802, 670.2721955542529, 339.08810644312905, 268.59706064619024]
  resolution: [640, 480]
  rostopic: /cam0/mine_raw
cam1:
  T_cn_cnm1:
  - [0.9908320195212902, 0.05448996374964259, 0.12362343200997924, 0.07896560306178048]
  - [-0.04584105472306963, 0.9963679251516184, -0.07176040294575482, -0.0007754973017808575]
  - [-0.12708464420707902, 0.06543547646058061, 0.9897311208743204, 0.008097858581766097]
  - [0.0, 0.0, 0.0, 1.0]
  cam_overlaps: [0]
  camera_model: pinhole
  distortion_coeffs: [-0.02799519569572124, -0.3535515683042248, 0.013156194855475018, 0.0414613191086705]
  distortion_model: radtan
  intrinsics: [657.2120506645199, 674.8711579504172, 283.17302902952315, 254.06220191268537]
  resolution: [640, 480]
  rostopic: /cam1/mine_raw

`

I want to add this configuration to Vins Fusion to run it with directly with my cameras. My problem is that the configuration yaml files that i have found from vins fusion with stereo_cameras (https://github.com/HKUST-Aerial-Robotics/VINS-Fusion/blob/master/config/A3_ptgrey/a3_ptgrey_stereo_config.yaml ) are different  than my calibration output .I am not using an IMU in my setup.

**Comment by goldbattle** [comment]
I recommend opening an issue that software platform on how to create their configuration file.

If you just need the frame-to-frame then `T_cn_cnm1` and each cameras' intrinsics should be sufficient?
