### ISSUE TITLE
Vicon-IMU calibration

### ISSUE THREAD

**Issue by dmalyuta** [ethz-asl/kalibr#93]
Is there an easy possibility for extending the camera-IMU calibration to Vicon-IMU calibration? In particular, to determine the IMU frame's pose with respect to the Vicon frame assigned to the quadcopter via the object creation tool in Vicon's Tracker software. This would make it easy to precisely define the Vicon object such that it corresponds, to within a tight tolerance, to the actual IMU frame - which is very useful in many applications.

**Comment by goldbattle** [comment]
Kalibr doesn't support this currently. You can checkout this project if you still need this:
https://github.com/rpng/vicon2gt
