### ISSUE TITLE
The acc errors appear to be all zero.

### ISSUE THREAD

**Issue by Userskii** [ethz-asl/kalibr#97]
I did a combined VI sensor calibration using the Camera-IMU calibration tool. However the gyro and acc errors are almost zero somehow. This is shown like 

Calibration results
===================
Normalized Residuals
----------------------------
Reprojection error (cam0):     mean 0.161373177542, median 0.143201264718, std: 0.100674912244
Reprojection error (cam1):     mean 0.16662511419, median 0.146514104122, std: 0.104168779993
Gyroscope error (imu0):        mean 3.72979172913e-10, median 2.24605333102e-10, std: 1.22841183962e-09
Accelerometer error (imu0):    mean 8.98662346209e-10, median 4.43878332656e-11, std: 1.53928329578e-08

What could be the possible cause for this? The imu0.csv as follows
[imu0.txt](https://github.com/ethz-asl/kalibr/files/957551/imu0.txt)

**Comment by Userskii** [comment]
The imu data is not collected correctly.

**Comment by bdjohnson529** [comment]
I am having the same issue. How did you correct your setup to collect IMU data properly?

**Comment by MerlotQ** [comment]
@bdjohnson529 make sure that the sampling rate is correct
