### ISSUE TITLE
make code lighter

### ISSUE THREAD

**Issue by skanti** [ethz-asl/kalibr#98]
I am waiting now 20 min to get the build done...

**Comment by v-mehta** [comment]
I had to wait a long time too. Using -j 2 option and then compiling one package at a time following the dependency tree worked fine.

**Comment by hitimo** [comment]
@skanti 

- use [ccache](https://ccache.samba.org/) to cache your builds and to compile faster
- use [cde](https://github.com/ethz-asl/kalibr/wiki/downloads) if you are not changing the source code and you are okay with the old version
- make sure you compile with all threads, e.g. `catkin build -j8`

I don't see dependencies that can be removed..
