### ISSUE TITLE
ERROR:  initialization of focal length 

### ISSUE THREAD

**Issue by einspyon** [ethz-asl/kalibr#99]
Extracted corners for 388 images (of 519 images)                              
[ERROR] [1493897823.130380]: initialization of focal length for cam with topic /cam0/image_raw failed  
	Projection initialized to: [ nan  nan  nan  nan]
	Distortion initialized to: [ nan  nan  nan  nan]

why? beg for help

**Comment by skohlbr** [comment]
I ran into the same problem and implemented a hack that just generates a guess if kalibr wasn't able to generate an inital guess, see here: https://github.com/tu-darmstadt-ros-pkg/kalibr/commit/2822f6a6f47b92b600de42fd1e82915f1b0b2fd7

This approach worked fine when calibrating a multi-camera system, even though I just put in 400 as a magic number for the focal length initial estimate.

**Comment by Doodleshr** [comment]
same error here, does anyone know how to solve it under CDE?

**Comment by utkarsh447** [comment]
> same error here, does anyone know how to solve it under CDE?

Hi, Did anyone fine solution for CDE? As the file mentioned in this commit [tu-darmstadt-ros-pkg@2822f6a](https://github.com/tu-darmstadt-ros-pkg/kalibr/commit/2822f6a6f47b92b600de42fd1e82915f1b0b2fd7)  is not present in kalibr-cde.

**Comment by LarryDong** [comment]
I tried to solve this problem for CDE version by manually give an initial guess. Please check [issue-367](https://github.com/ethz-asl/kalibr/issues/367#issuecomment-846945763)

I set cam0's distortion to all zeros and the projection estimated by its focal length & resolution, like this:
```bash
cameraList[0].geometry.projection().setParameters(np.array(1600,1706,640,512]))
cameraList[0].geometry.projection().distortion().setParameters(np.array([0,0,0,0]))
```
Since my sensor is 1/3'' inch, with a resolution of 1280x1024, and focus length should be 6mm. So 1600 is calculated by: 6mm/4.8mmx1280, 1706=6/3.6x1024, and 640&512 is half the resolution.

The final result from kalibr is: [2094.6, 2114.3, 497.3, 464.8], which seems reasonable.

Hope it helps.

**Comment by Horizon-42** [comment]
> > > I tried to solve this problem for CDE version by manually give an initial guess. Please check [issue-367](https://github.com/ethz-asl/kalibr/issues/367#issuecomment-846945763)
> > > I set cam0's distortion to all zeros and the projection estimated by its focal length & resolution, like this:
> > > ```shell
> > > cameraList[0].geometry.projection().setParameters(np.array(1600,1706,640,512]))
> > > cameraList[0].geometry.projection().distortion().setParameters(np.array([0,0,0,0]))
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Since my sensor is 1/3'' inch, with a resolution of 1280x1024, and focus length should be 6mm. So 1600 is calculated by: 6mm/4.8mmx1280, 1706=6/3.6x1024, and 640&512 is half the resolution.
> > > The final result from kalibr is: [2094.6, 2114.3, 497.3, 464.8], which seems reasonable.
> > > Hope it helps.
> > 
> > 
> > can you tell me which line you changed in the cde file? I insert this two line in the main while loop, but it did not work.
> > thank you!!!
> 
> Yes I put those line just in the while true loop.
> `kalibr_calibrate_cameras` file, `main()` function, `while true:` loop. I guess the line number is 208 here.

thanks!

**Comment by goldbattle** [comment]
Should be fixed via manual specification: https://github.com/ethz-asl/kalibr/pull/346

**Comment by peci1** [comment]
#757 brings the option to specify focal length on command line in advance.
